'use strict';
(()=>{
const M=window.CHERUB_MANIFEST||{appVersion:'2026.09.10.4'};
const PK='cherub.progress.v7',SK='cherub.session.v7',NK='cherub.notes.v1';
const BASELINE_COUNT=20,BASELINE_VERSION='20q-cism-format-v2',QUESTION_FORMAT_VERSION='cism-management-v2';
const D={1:'Information Security Governance',2:'Information Security Risk Management',3:'Information Security Program',4:'Incident Management'};
const W={1:.17,2:.20,3:.33,4:.30},N={1:26,2:30,3:49,4:45};
const TOP={1:['Business alignment','Governance / authority','Roles & accountability','Strategy'],2:['Risk assessment','Risk response','Residual risk / ownership','Monitoring / reporting'],3:['Program alignment','Control design / selection','Implementation','Testing / effectiveness'],4:['Readiness / planning','Investigation / classification','Containment decisions','Recovery']};
const REL={1:['Business objectives → security strategy','Governance → decision rights','Risk appetite → tolerance','Business owner → risk acceptance','Metrics → executive decisions'],2:['Threat/vulnerability → risk assessment','Controls → residual risk','Residual risk → risk owner','Treatment → monitoring','Material change → reassessment'],3:['Requirements → program objectives','Program → control design','Implementation → operation','Operation → testing','Testing → effectiveness','Effectiveness → metrics'],4:['BIA → RTO/RPO','RTO/RPO → recovery strategy','Plan → recovery test','Incident → classify/triage','Contain → eradicate → recover','Post-incident review → corrective action']};
const RULES={
1:[
['Business alignment',0,'Map security priorities to business objectives, enterprise risk, and accountable decision rights.','Prioritize the technical solution with the broadest coverage','Map the decision to business objectives, risk appetite, and accountable ownership','Let security accept the business risk','Delay until every policy and standard is perfect','business-alignment'],
['Risk ownership',2,'Material business risk is accepted by the accountable business owner; security advises.','Ask internal audit to accept the risk','Have the security manager accept it','Present risk and treatment choices to the accountable business owner','Transfer ownership to the technology vendor','wrong-owner'],
['Risk appetite',1,'Translate appetite into measurable tolerance and decision thresholds before changing controls.','Increase every security control immediately','Translate appetite into tolerances, thresholds, and prioritized gaps','Wait for the next annual audit','Use vulnerability severity as the enterprise risk threshold','appetite-vs-tolerance'],
['Governance metrics',0,'Use outcome metrics tied to business risk and objectives rather than activity counts.','Report number of alerts processed','Report number of security tools deployed','Report reduction in business-impacting risk against approved targets','Report number of awareness emails sent','activity-vs-outcome'],
['Decision authority',1,'Define who can make material risk decisions and how escalation works.','Give all analysts authority to stop business services','Define decision rights and escalation thresholds','Move all decisions to internal audit','Require unanimous technical-team approval','authority'],
['Compliance scope',3,'Determine applicability and affected business scope before choosing controls.','Apply every new requirement enterprise-wide immediately','Determine applicability, obligations, and affected assets first','Ask a vendor to define the legal scope','Treat compliance as identical to risk','compliance-vs-risk'],
['Business case',3,'Compare investments using risk reduction, obligations, dependencies, and strategic value.','Choose the lowest-cost control','Choose the highest-rated vendor','Compare expected risk reduction and strategic value','Choose the project with the most technical features','business-value'],
['Policy governance',1,'Policy exceptions should be governed, time-bound, risk-based, and owned.','Ban all exceptions','Approve permanent exceptions informally','Use a documented, risk-based, time-bound exception with accountable approval','Let administrators approve their own exceptions','exception-governance'],
['Board reporting',0,'Executives need decision-oriented information in business terms.','Provide raw event logs','Present business impact, trend, options, and decisions required','Send only vulnerability counts','Report every technical issue at equal priority','executive-reporting'],
['M&A governance',3,'Assess equivalence and risk before replacing an acquired company’s controls.','Replace every acquired control immediately','Assess objectives, mandatory requirements, and control equivalence first','Let the acquired company remain permanently independent','Ask audit to operate the integration','assessment-before-action']],
2:[
['Risk assessment',0,'Assess likelihood and business impact in the current control environment before treatment.','Remediate every vulnerability immediately','Assess likelihood, impact, exposure, and existing controls first','Accept the risk before analysis','Use the vulnerability score as the risk decision','assessment-before-treatment'],
['Risk criteria',0,'Use common scales and impact guidance tied to business objectives.','Always use the highest rating','Define common criteria, scales, and business impact guidance','Average conflicting ratings without analysis','Let security assign every business impact','risk-criteria'],
['Third-party risk',0,'Evaluate legal, contractual, resilience, control, and data-handling risk against enterprise requirements.','Rely on vendor marketing material','Assess the provider against enterprise risk and compliance requirements','Require identical tools to your environment','Treat one penetration test as sufficient','third-party-assurance'],
['Risk treatment',1,'Present viable treatment options and support an informed owner decision.','Implement the most expensive control','Validate analysis and present treatment options to the accountable owner','Delete the risk if the owner rejects a control','Have audit choose the treatment','wrong-owner'],
['Residual risk',2,'Residual risk reflects the likelihood and impact remaining after effective controls.','Set residual risk to zero when any control exists','Reassess likelihood and impact based on actual control effectiveness','Reduce likelihood and impact by the same amount automatically','Ignore compensating controls','implemented-vs-effective'],
['Risk register',3,'A useful register prioritizes decisions, ownership, thresholds, and treatment status.','Sort risks alphabetically','Prioritize by impact, likelihood, ownership, treatment status, and tolerance','Add every vulnerability as a separate executive risk','Hide accepted risks','risk-reporting'],
['Risk escalation',1,'Risks above tolerance require explicit escalation and accountable decisions.','Lower the rating until treatment is available','Escalate with interim options and explicit decision requirements','Assume management accepts the risk','Remove the risk from reporting','risk-escalation'],
['Risk monitoring',3,'Reassess when assets, threats, controls, impact, or assumptions materially change.','Assess only once per year regardless of change','Refresh assessment after significant change and monitor key indicators','Replace monitoring with audits','Keep ratings fixed for trend consistency','change-reassessment'],
['Risk reporting',3,'Aggregated risk needs methodology, uncertainty, drivers, and drill-down.','Give one number without assumptions','Provide aggregation with assumptions, uncertainty, and material drivers','Refuse to summarize risk','Use the highest CVSS score as enterprise risk','risk-reporting'],
['Cloud assurance',0,'Determine whether available independent assurance is sufficient for your obligations and risk.','Reject any provider without custom audit rights','Assess whether available assurance satisfies specific requirements','Accept any famous cloud provider automatically','Perform unauthorized testing','assurance-sufficiency']],
3:[
['Program alignment',0,'Program capabilities should trace to business requirements, risks, obligations, and priorities.','Buy a larger SIEM first','Map program objectives and capabilities to business and risk requirements','Add controls until every framework item is covered','Let technical teams set priorities independently','program-alignment'],
['Control effectiveness',3,'Measure whether controls change relevant risk outcomes, not merely whether they are installed.','Count implemented controls only','Measure control effectiveness against intended risk outcomes','Use vendor certifications as proof of effectiveness','Increase tool count','implemented-vs-effective'],
['Control lifecycle',2,'A control needs ownership, operation, monitoring, support, and maintenance before rollout.','Deploy once technical testing passes','Resolve ownership, support, monitoring, and lifecycle requirements','Assign control operation to audit','Ignore operations concerns','control-lifecycle'],
['Security architecture',0,'Architecture translates requirements into coherent principles and target capabilities.','Document product versions only','Translate business and security requirements into design principles and capabilities','Replace risk management with architecture','Make every system identical','architecture-alignment'],
['Awareness effectiveness',3,'Measure behavior and risk outcomes rather than attendance or activity volume.','Count training slides','Measure observed behavior change and reporting outcomes','Count reminder emails','Use attendance as the sole metric','activity-vs-outcome'],
['Roadmap prioritization',0,'Prioritize by business risk reduction, obligations, dependencies, and strategic value.','Choose whichever vendor offers a discount','Prioritize by risk reduction, obligations, dependencies, and strategic value','Fund teams in alphabetical order','Prioritize by complaint volume','business-value'],
['Standards',1,'Use enterprise control objectives and minimum requirements with governed exceptions.','Mandate one vendor for every control','Define enterprise minimum requirements and governed exceptions','Rely on audits to define standards','Let each business unit define unrelated objectives','policy-vs-standard'],
['Key-person risk',0,'Build sustainable capability with documentation, cross-training, and succession.','Give the expert permanent exception authority','Reduce concentration risk through documentation and cross-training','Outsource immediately without analysis','Accept the dependency because performance is good','resource-risk'],
['Requirements',0,'Security should define requirements and advise; accountable business owners retain risk decisions.','Security should own project business risk','Provide requirements and risk advice to the accountable owner','Security should guarantee zero breach risk','Have audit approve the technical design','wrong-owner'],
['Resource management',0,'Program resources should be allocated according to risk, business value, and critical dependencies.','Allocate evenly to every request','Allocate based on prioritized risk and business value','Fund only the newest technologies','Let vendors decide the roadmap','business-value'],
['Change integration',2,'Security requirements should be embedded in business and technology change processes.','Review security only after deployment','Integrate security requirements early in the change lifecycle','Block all change until annual review','Delegate every security decision to developers','security-by-design'],
['Control exceptions',1,'Exceptions should preserve the control objective through compensating measures and accountable approval.','Ignore exceptions once approved','Use risk-based approval, compensating controls, and expiry','Make exceptions permanent','Let requestors self-approve','exception-governance'],
['Program metrics',3,'Use leading and lagging measures tied to objectives and risk outcomes.','Report activity counts only','Use measures that show capability, outcomes, and business risk trend','Use one metric for all stakeholders','Avoid trend data','activity-vs-outcome'],
['Vendor integration',2,'Third-party services need clear requirements, ownership, monitoring, and exit considerations.','Treat signed contracts as sufficient','Define security requirements, monitoring, ownership, and exit needs','Let procurement own all cyber risk','Skip monitoring after onboarding','third-party-assurance'],
['Data protection',1,'Controls should follow data classification, business use, legal obligations, and risk.','Encrypt everything identically without context','Apply protection based on classification, obligations, and business risk','Let users choose controls individually','Use retention as the only protection decision','classification-driven-controls'],
['Resilience',0,'Program design should account for continuity, dependencies, recovery objectives, and failure modes.','Focus only on prevention','Design for resilience, recovery objectives, and critical dependencies','Assume high availability equals resilience','Make security own all business continuity decisions','resilience']],
4:[
['Incident activation',1,'Activate the process, establish scope/severity, roles, coordination, and decision authority first.','Immediately rebuild every affected system','Activate the incident process and establish scope, severity, roles, and coordination','Notify the media first','Delete suspicious files','scenario-state'],
['Containment authority',2,'Material containment decisions need predefined business/incident authority and escalation.','Let the fastest analyst decide','Use predefined accountable authority and escalation for business-impacting containment','Let the vendor decide','Wait for internal audit','authority'],
['Classification',1,'Classification enables consistent prioritization, escalation, response, and communication.','Use classification only for reporting style','Classify to drive prioritization, escalation, response, and communication','Replace root-cause analysis with classification','Eliminate professional judgment','classification'],
['Notification',1,'Potential notification obligations should trigger legal/privacy coordination early while facts and timelines are preserved.','Notify every regulator immediately','Engage legal/privacy decision processes early and preserve facts/timelines','Wait until all technical investigation is complete','Ask the attacker for confirmation','notification-sequence'],
['Eradication and recovery',3,'Validate eradication and recovery criteria before controlled restoration.','Restore immediately after containment','Validate eradication and recovery criteria before controlled restoration','Close the incident after containment','Stop monitoring during recovery','scenario-state'],
['Lessons learned',3,'Address technical and nontechnical causes, business/process/control issues, and accountable corrective actions.','Document malware details only','Identify technical and business/process/control causes with accountable corrective actions','Close once systems are restored','Leave actions unassigned','post-incident-improvement'],
['Exercises',0,'Exercises should validate decision rights, dependencies, communications, procedures, and recovery assumptions.','Measure exercise success by attendance','Use exercises to validate roles, authority, dependencies, and procedures','Run the same scenario without remediation','Limit exercises to SOC analysts','evidence-vs-documentation'],
['Evidence handling',1,'Preserve integrity, provenance, chronology, and legal requirements while supporting response.','Delete artifacts after imaging','Preserve evidence integrity, chronology, and handling requirements','Let every responder copy evidence freely','Prioritize convenience over provenance','evidence-handling'],
['Recovery validation',3,'Recovery points and systems must be trustworthy and monitored so compromise is not reintroduced.','Restore the newest backup without checking it','Validate the recovery source and monitor restoration for recurrence','Delete all backups after an incident','Ask audit to perform restoration','recovery-validation'],
['IR metrics',3,'Measure detection, escalation, containment, recovery, communication, and corrective-action closure.','Count pages in the response plan','Measure response outcomes and closure of corrective actions','Count tools in the SOC','Use incident labels as the main success metric','activity-vs-outcome'],
['Crisis communication',2,'Use predefined, authorized communication channels and coordinated messaging.','Allow any responder to speak publicly','Use authorized communication roles and coordinated messaging','Delay all internal communication until closure','Let vendors issue statements for the organization','authority'],
['Incident ownership',2,'Technical responders execute tasks, while accountable incident/business leadership owns material decisions.','Make analysts own all business risk','Separate technical execution from accountable material decision authority','Let audit command the incident','Let legal run technical containment','wrong-owner'],
['Detection escalation',1,'Alert severity alone is insufficient; escalation should reflect business context and incident criteria.','Escalate only by tool severity','Use validated incident criteria and business impact to drive escalation','Escalate every alert to executives','Ignore low-severity alerts permanently','technical-vs-business'],
['Post-incident improvement',3,'Lessons learned should feed program, control, architecture, training, and governance improvements.','Archive the report and make no changes','Track corrective actions into program and control improvements','Only update the incident plan','Treat each incident as isolated','post-incident-improvement'],
['Playbooks',0,'Playbooks should guide repeatable action while preserving decision points and escalation.','Make playbooks fully automatic for all business decisions','Use playbooks for repeatable actions with explicit decision and escalation points','Avoid playbooks because incidents differ','Let each responder improvise without common steps','authority']]
};
const ORGS=['global manufacturer','regional bank','healthcare provider','cloud software company','government contractor','online retailer','university','insurance company','logistics company','financial services firm','research organization','energy company'];
const TRIG=['after a material business change','while preparing a time-sensitive initiative','before a high-impact service decision','after an operating concern was raised','while budgets are constrained','after a requirement changes','during routine executive oversight','after repeated performance concerns','when a key dependency changes','after a significant business disruption','while modernizing a critical service','during annual planning'];
const STATES=['Available evidence is incomplete and stakeholders interpret it differently','A recommendation is needed before the next decision point','The accountable owner needs options and consequences','Technical teams have proposed a quick response','The current approach exists but its outcome is uncertain','Conditions differ materially from the last decision'];
const ACTORS={1:['business executive','governance lead','program sponsor','business owner'],2:['business owner','enterprise risk lead','service owner','program sponsor'],3:['program lead','control owner','business service lead','delivery lead'],4:['response lead','continuity lead','business executive','legal adviser']};
const DISTRACTORS={
1:['Obtain independent assurance that the proposed approach complies with established requirements','Prepare implementation milestones for the preferred technical approach','Benchmark the proposal against comparable organizations before deciding','Expand reporting on current operational activity before changing direction','Request a detailed control design before clarifying decision authority','Update the supporting procedure without changing the governing decision'],
2:['Obtain additional technical findings before considering the business consequence','Select the option with the lowest implementation cost','Update the risk record without changing the current treatment decision','Use the prior assessment rating to preserve reporting consistency','Request independent assurance of the control design before deciding','Prioritize the issue using technical severity and the current remediation backlog'],
3:['Measure implementation activity before evaluating the intended outcome','Add a new technical capability before confirming the operating need','Request independent assurance before assigning operational ownership','Use the previous project design as the standard approach','Increase training volume before confirming the behavior to change','Allocate resources based on current project readiness and available teams'],
4:['Expand technical investigation before applying the defined decision criteria','Prepare a stakeholder update before confirming the required action','Begin restoration before validating the recovery conditions','Request independent assurance before assigning response ownership','Use the response approach applied to a prior event with similar technical symptoms','Close the event after documenting the technical symptoms']
};
const SCENARIOS={
1:['Leadership is deciding how a proposed approach should support a high-priority business outcome.','A business unit requests an exception that could affect a material customer commitment.','Two parts of the organization use different approval paths and report conflicting information.','Leaders see high activity but cannot tell whether the outcome they care about is improving.','A new obligation may apply to only part of the organization and its shared services.'],
2:['A critical business service will rely on a changed operating arrangement after its last assessment.','A high-value process has several weaknesses, but existing safeguards may already reduce the exposure.','The accountable owner prefers one option while technical teams recommend a more costly alternative.','A decision log contains many entries but does not distinguish material choices from routine findings.','New information conflicts with assumptions used in a prior decision about a customer-facing service.'],
3:['A major initiative is moving forward before the intended business outcomes are fully agreed.','A capability is in place, but the team cannot show ownership, evidence, or how results are monitored.','A new service is being adopted quickly without clear responsibilities, evidence expectations, or exit needs.','Participation is high, but desired behavior has not changed and important reports arrive late.','A dashboard shows implementation activity and ticket volume but not whether the intended outcome improved.'],
4:['A serious disruption affects a critical service while leaders debate whether to interrupt a shared capability.','A developing situation may create obligations, but facts and the timeline are still being established.','Teams want to restore service immediately although the proposed restoration point has not been validated.','A recent exercise exposed unclear authority, outdated contacts, and dependencies missing from plans.','A review identified recurring failures, but corrective actions have no owner or due date.']
};
const DIAGNOSTIC_ITEMS=[
{d:1,concept:'Business alignment',rel:'Business objectives → security strategy',mistake:'technology-before-business',stem:'Senior leadership is reviewing a proposed security investment for a business expansion. Which information should MOST influence the recommendation?',o:['The capability comparison between available products','The connection to business objectives and material risk','The number of security events reported last quarter','The implementation preferences of technical teams'],a:1,why:'A management recommendation should show how the investment supports business objectives and reduces material risk.'},
{d:1,concept:'Governance metrics',rel:'Metrics → executive decisions',mistake:'activity-vs-outcome',stem:'Executives receive a monthly security dashboard but cannot determine whether risk is improving. Which addition would be MOST useful?',o:['A count of completed security projects','A trend in business-impacting risk against approved targets','A list of security tools deployed during the quarter','A total of tickets closed by the security team'],a:1,why:'Outcome and risk trends support executive decisions; activity counts do not show whether the intended result improved.'},
{d:1,concept:'Decision authority',rel:'Governance → decision rights',mistake:'wrong-owner',stem:'A material exception would affect a customer commitment. The security team has completed its analysis. Who should make the acceptance decision?',o:['The accountable business owner under the defined approval process','The internal audit leader because the exception affects controls','The security architect because the analysis is technical','The service provider because it operates the affected capability'],a:0,why:'Security advises and analyzes; the accountable business owner accepts material business risk through defined governance.'},
{d:1,concept:'Policy governance',rel:'Governance → decision rights',mistake:'policy-vs-procedure',stem:'Several business units use inconsistent approval practices for the same type of security exception. Which action is MOST appropriate?',o:['Define common decision rights, criteria, and escalation thresholds','Allow each unit to retain the process that is fastest','Move approval responsibility to the technical operations team','Require every exception to be reviewed by internal audit'],a:0,why:'Common decision rights and criteria create consistent, accountable governance while preserving appropriate escalation.'},
{d:1,concept:'Risk appetite',rel:'Risk appetite → tolerance',mistake:'appetite-vs-tolerance',stem:'Leadership has set an enterprise risk appetite but teams cannot apply it to operational decisions. What should be established next?',o:['A list of every security control in use','Measurable tolerances and escalation thresholds','A catalogue of recent security incidents','A technical baseline for all systems'],a:1,why:'Risk appetite becomes usable through measurable tolerances and thresholds that guide decisions and escalation.'},
{d:2,concept:'Risk assessment',rel:'Threat/vulnerability → risk assessment',mistake:'assessment-before-treatment',stem:'A critical process has several identified weaknesses, but existing safeguards may reduce their effect. Before selecting treatment, what is MOST important?',o:['Estimate likelihood and business impact in the current control environment','Rank the weaknesses by the number of systems affected','Select the safeguard with the lowest implementation cost','Ask the technical team to remove the highest-rated weakness'],a:0,why:'Treatment should be based on likelihood and impact after considering the actual control environment.'},
{d:2,concept:'Risk criteria',rel:'Threat/vulnerability → risk assessment',mistake:'inconsistent-criteria',stem:'Different business units assign different impact ratings to comparable events. Which improvement would MOST strengthen the assessment process?',o:['A common impact scale tied to business objectives','A requirement to use the highest proposed rating','A separate scale for each business unit','A rule that technical teams set all impact ratings'],a:0,why:'Common, business-aligned criteria make risk assessments comparable and decision-ready.'},
{d:2,concept:'Risk treatment',rel:'Residual risk → risk owner',mistake:'wrong-owner',stem:'Analysis shows that a proposed safeguard would reduce risk but would delay a high-priority initiative. What is the MOST appropriate next step?',o:['Present treatment options and residual consequences to the accountable owner','Implement the safeguard because it produces the largest reduction','Defer the initiative until every uncertainty is removed','Ask internal audit to choose the treatment option'],a:0,why:'The accountable owner needs analyzed options and residual consequences to make the business risk decision.'},
{d:2,concept:'Residual risk',rel:'Controls → residual risk',mistake:'implemented-vs-effective',stem:'A safeguard has been implemented for a high-value service. What is MOST important when determining the remaining risk?',o:['Whether the safeguard is operating effectively against the relevant scenario','Whether the safeguard was delivered within the planned budget','Whether the service has passed a technical configuration review','Whether similar organizations use the same safeguard'],a:0,why:'Residual risk depends on the likelihood and impact remaining after effective controls, not simply on implementation.'},
{d:2,concept:'Risk monitoring',rel:'Material change → reassessment',mistake:'change-reassessment',stem:'A key dependency supporting a critical service changes materially after the latest assessment. What is the MOST appropriate response?',o:['Reassess the affected risk assumptions and treatment decision','Keep the prior rating to preserve year-over-year comparison','Wait for the scheduled annual review','Add the change to the next audit plan'],a:0,why:'A material change can invalidate assessment assumptions and should trigger reassessment.'},
{d:3,concept:'Program alignment',rel:'Requirements → program objectives',mistake:'solution-before-requirements',stem:'A major initiative is ready to select security capabilities, but the intended business outcome is not yet agreed. What should occur before selection?',o:['Define the relevant business requirements, risk, and obligations','Select the most mature capability and refine requirements later','Ask each technical team to select its preferred capability','Use the previous initiative as the design baseline'],a:0,why:'Program capabilities must trace to agreed business requirements, risk, and obligations.'},
{d:3,concept:'Control effectiveness',rel:'Testing → effectiveness',mistake:'implemented-vs-effective',stem:'A new control is operating, but management asks whether it has achieved its purpose. Which evidence is MOST useful?',o:['Evidence that the intended risk outcome has improved','The date on which the control was deployed','The number of staff trained to use the control','The vendor rating of the control product'],a:0,why:'Control effectiveness is demonstrated by evidence of the intended risk outcome, not installation activity.'},
{d:3,concept:'Resource management',rel:'Requirements → program objectives',mistake:'equal-allocation',stem:'Funding is limited and several security improvements compete for support. Which basis is MOST appropriate for prioritization?',o:['Expected risk reduction, business value, obligations, and dependencies','The number of requests submitted by each team','The age of the technology used by each team','The order in which improvement requests were received'],a:0,why:'Program resources should be allocated according to risk reduction, business value, obligations, and critical dependencies.'},
{d:3,concept:'Control lifecycle',rel:'Implementation → operation',mistake:'deployment-is-completion',stem:'A capability passed technical testing, but no owner is assigned to operate it or review its results. What should be addressed before broad rollout?',o:['Ownership, operating evidence, monitoring, and support responsibilities','A larger implementation team to accelerate deployment','A new technical test using more production data','A formal request for internal audit to operate the capability'],a:0,why:'A sustainable control requires ownership, operation, monitoring, support, and evidence throughout its lifecycle.'},
{d:3,concept:'Awareness effectiveness',rel:'Effectiveness → metrics',mistake:'activity-vs-outcome',stem:'Awareness participation is high, yet the behavior the program intends to change has not improved. What should management measure?',o:['Observed behavior and reporting outcomes tied to the objective','The number of training sessions delivered','The completion rate for the training module','The number of awareness messages distributed'],a:0,why:'Effectiveness is measured through behavior and risk outcomes, not attendance or communication volume.'},
{d:4,concept:'Classification',rel:'Incident → classify/triage',mistake:'action-before-assessment',stem:'A potentially serious security event is reported, but available information is incomplete. What should guide the initial response decision?',o:['Validated criteria for scope, severity, and business impact','The technical tool that generated the alert','The number of responders currently available','The amount of media attention the event may receive'],a:0,why:'Classification using validated criteria and business impact enables consistent prioritization and escalation.'},
{d:4,concept:'Containment authority',rel:'Contain → eradicate → recover',mistake:'authority',stem:'Interrupting a shared capability may limit further harm but could disrupt critical operations. What is MOST important before the decision is made?',o:['Use the predefined authority and escalation process for business-impacting containment','Allow the fastest available responder to make the decision','Wait until every technical detail is known','Ask the service provider to determine the acceptable business impact'],a:0,why:'Material containment decisions require predefined accountable authority and escalation that considers business impact.'},
{d:4,concept:'Recovery validation',rel:'RTO/RPO → recovery strategy',mistake:'restore-without-validation',stem:'Teams are ready to restore a critical service, but the proposed recovery source has not been validated. What is MOST appropriate?',o:['Validate the recovery source and restoration criteria before controlled recovery','Restore immediately and monitor for issues afterward','Use the newest available copy because it minimizes data loss','Ask internal audit to authorize the restoration'],a:0,why:'Recovery must use a trustworthy source and validated criteria so the problem is not reintroduced.'},
{d:4,concept:'Evidence handling',rel:'Incident → classify/triage',mistake:'evidence-integrity',stem:'A developing event may require later legal action. Which objective is MOST important while responders collect relevant information?',o:['Preserve integrity, provenance, chronology, and handling records','Collect the greatest possible volume of information immediately','Provide all responders unrestricted copies of the information','Delay collection until the technical cause is confirmed'],a:0,why:'Evidence must retain integrity, provenance, and chronology to remain reliable and usable.'},
{d:4,concept:'Lessons learned',rel:'Post-incident review → corrective action',mistake:'close-without-improvement',stem:'A significant event is resolved, but the review identifies recurring process and control failures. What should happen next?',o:['Assign accountable corrective actions and track them into program improvement','Archive the report after documenting the technical cause','Update only the response procedure used during the event','Schedule another exercise before assigning any actions'],a:0,why:'Lessons learned should create accountable corrective actions that improve program, control, and governance outcomes.'}
];
function prng(seed){let x=seed>>>0;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296)}
function shuffle(a,r=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function whyWrong(t){let s=t.toLowerCase();if(s.includes('audit'))return 'Audit provides independent assurance; it normally does not own the business decision or operate the control.';if(s.includes('vendor'))return 'A vendor can support execution, but accountability and enterprise risk decisions remain with the organization.';if(s.includes('immediately')||s.includes('first'))return 'This acts before the required management context, authority, or evidence is established.';if(s.includes('every')||s.includes('all '))return 'This is overly absolute and ignores risk, scope, business context, or proportionality.';if(s.includes('wait')||s.includes('delay'))return 'This delays a decision that should be governed through defined authority and risk-based action.';return 'This may be reasonable in another context, but it does not best satisfy the management objective, sequence, or accountable decision required here.'}
function makeQ(d,i,seed,label){const r=prng(seed*1000+d*100+i),rule=RULES[d][(i+seed)%RULES[d].length],pool=DISTRACTORS[d].filter(x=>!x.toLowerCase().includes(rule[0].toLowerCase())).slice(),base=[rule[4],...shuffle(pool,r).slice(0,3)],order=shuffle([0,1,2,3],r),o=order.map(x=>base[x]),a=o.indexOf(rule[4]),qual=(i+seed)%2?'BEST':'MOST appropriate',org=ORGS[Math.floor(r()*ORGS.length)],tr=TRIG[Math.floor(r()*TRIG.length)],st=STATES[Math.floor(r()*STATES.length)],frame=SCENARIOS[d][(i+seed)%SCENARIOS[d].length],actor=ACTORS[d][(i+seed)%ACTORS[d].length],rels=REL[d];const correctReason=rule[2];const rr=shuffle([correctReason,'This option is a valid management activity, but it is aimed at a different decision or stage.','This option may add useful information, but it does not resolve the decision described.','This option addresses implementation or assurance rather than the accountable management objective.'],r);return{id:`${label}-D${d}-${String(i+1).padStart(3,'0')}`,d,topic:TOP[d][rule[1]],concept:rule[0],mistake:rule[7],rel:rels[(i+seed)%rels.length],difficulty:(i+seed)%2?'Hard':'Harder',scenarioFamily:frame,actor,formatVersion:QUESTION_FORMAT_VERSION,stem:`At a ${org}, a ${actor} needs a recommendation ${tr}. ${frame} ${st}. Which action is ${qual}?`,o,a,why:rule[2],whyOptions:o.map((x,j)=>j===a?rule[2]:whyWrong(x)),reasonOptions:rr,reasonAnswer:rr.indexOf(correctReason),qualifier:qual};}
function makeBank(seed,label){let out=[];for(let d=1;d<=4;d++)for(let i=0;i<N[d];i++)out.push(makeQ(d,i,seed,label));return shuffle(out,prng(seed+77));}
function makePretest(){return shuffle(DIAGNOSTIC_ITEMS.map((item,i)=>{let r=prng(8100+i),order=shuffle([0,1,2,3],r),o=order.map(n=>item.o[n]),a=o.indexOf(item.o[item.a]),reasonOptions=shuffle([item.why,'This option favors technical capability over the management objective.','This option may be useful, but it does not resolve the accountable decision in the scenario.','This option addresses a valid activity at a different stage of the decision.'],r);return{...item,id:`PRE-D${item.d}-${String(i+1).padStart(3,'0')}`,topic:'',difficulty:i%2?'Harder':'Hard',formatVersion:QUESTION_FORMAT_VERSION,o,a,whyOptions:o.map((x,n)=>n===a?item.why:whyWrong(x)),reasonOptions,reasonAnswer:reasonOptions.indexOf(item.why),qualifier:'BEST'}}),prng(178));}
const BANKS={pretest:makePretest(),week3:makeBank(303,'W3'),week4:makeBank(404,'W4'),week5:makeBank(505,'W5'),week6:makeBank(606,'W6')};
const base=()=>({schema:7,completedPretest:false,attempts:[],sessions:[],questionExposure:{},relationshipMastery:{},settings:{autoUpdate:true},updatedAt:Date.now()});
const load=()=>{try{let p={...base(),...JSON.parse(localStorage.getItem(PK)||'{}')};if(p.pretestVersion!==BASELINE_VERSION)p.completedPretest=false;return p}catch{return base()}};
const save=p=>{p.updatedAt=Date.now();localStorage.setItem(PK,JSON.stringify(p));renderDashboard();renderSchedule();};
const getSession=()=>{try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}};
const putSession=s=>localStorage.setItem(SK,JSON.stringify(s));
const clearSession=()=>localStorage.removeItem(SK);
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.menu button').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelector(`[data-v="${id}"]`)?.classList.add('active');if(id==='progress')renderProgress();if(id==='map')renderMap();if(id==='practice')renderPractice();if(id==='schedule')renderSchedule();if(id==='notes')renderNotes();if(id==='resources')renderResources();if(id==='settings')renderSettings();}window.show=show;
function attemptsForSession(id,p=load()){return p.attempts.filter(a=>a.sessionId===id)}
function weakDomains(p=load()){return [1,2,3,4].map(d=>{let a=p.attempts.filter(x=>x.d===d);return[d,a.length?a.filter(x=>x.ok).length/a.length:0]}).sort((a,b)=>a[1]-b[1]).map(x=>x[0])}
function makeAdaptive(){let p=load(),quota=[8,5,4,3],order=weakDomains(p),seed=Math.floor(Date.now()/86400000),pool=[];order.forEach((d,k)=>{for(let i=0;i<quota[k];i++)pool.push(makeQ(d,i+seed%37,700+seed+k,'ADP'))});return shuffle(pool,prng(seed));}
function start(mode){let p=load(),old=getSession();if(old&&old.bankVersion!==QUESTION_FORMAT_VERSION){clearSession();old=null;}if(mode!=='pretest'&&!p.completedPretest)return alert('Complete the 20-question cold diagnostic first.');if(old&&old.mode===mode&&(!(mode==='pretest')||old.ids.length===BASELINE_COUNT))return openSession(old);if(mode==='pretest'){if(old?.mode==='pretest')clearSession();p.attempts=p.attempts.filter(a=>a.mode!=='pretest');p.sessions=p.sessions.filter(x=>x.mode!=='pretest');p.completedPretest=false;delete p.pretestVersion;save(p);return createSession('pretest',BANKS.pretest,true)}if(mode==='adaptive')return createSession('adaptive',makeAdaptive(),true);if(/^week[3-6]$/.test(mode)){if(p.sessions.some(s=>s.mode===mode&&s.completed))return alert('That weekly full exam is already completed.');if(!confirm('This is a 150-question full exam. You may pause and resume it; answers remain hidden until completion. Start now?'))return;return createSession(mode,BANKS[mode],true)}}
function focusRuleIndices(d,focus){let words=String(focus||'').toLowerCase().match(/[a-z]{3,}/g)||[],scored=RULES[d].map((r,i)=>[i,words.reduce((n,w)=>n+(r.slice(0,3).join(' ').toLowerCase().includes(w)?1:0),0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);return scored.length?scored:[...RULES[d].keys()]}
function challengeContext(level){if(level<=7)return 'The decision scope and accountable owner are clear.';if(level<=14)return 'Two stakeholders disagree about timing, and the available evidence is incomplete.';return 'The business deadline is fixed, a third party is involved, competing risk objectives exist, and leadership needs an accountable recommendation with an interim option.'}
function startFocused(c){let p=load();if(!p.completedPretest)return alert('Complete the 20-question cold diagnostic first.');let d=Math.max(1,Math.min(4,+c.domain||1)),count=Math.max(5,Math.min(150,+c.count||10)),level=Math.max(1,Math.min(20,+c.level||10)),seed=Date.now()%100000,focus=c.concept||c.path||TOP[d][0],selected=focusRuleIndices(d,focus),pool=[];for(let i=0;i<Math.max(count*3,30);i++){let sourceIndex=selected[i%selected.length],q=makeQ(d,sourceIndex+i*RULES[d].length,900+level,`FOCUS-${d}`);q.focus=focus;q.concept=focus;q.rel=c.path||q.rel;q.level=Math.max(1,Math.min(20,level+((i%5)-2)));q.difficulty=q.level<=7?`Foundation ${q.level}/20`:q.level<=14?`Hard ${q.level}/20`:`Hardest ${q.level}/20`;q.stem=q.stem.replace('A decision involving '+RULES[d][sourceIndex][0].toLowerCase(),`A decision involving ${focus.toLowerCase()}`)+` ${challengeContext(q.level)}`;q.why=`For ${focus}, ${q.why.charAt(0).toLowerCase()+q.why.slice(1)}`;pool.push(q)}pool.sort((a,b)=>Math.abs(a.level-level)-Math.abs(b.level-level));createSession('focused',pool.slice(0,count),true)}window.CherubStartFocused=startFocused;
function createSession(mode,bank,resumable){let ids=Array.isArray(bank)?bank.map(x=>x.id):bank.ids,s={id:`${mode}-${Date.now()}`,mode,index:0,ids,startedAt:Date.now(),resumable,bankVersion:QUESTION_FORMAT_VERSION};if(mode==='adaptive'||mode==='focused')s.bank=bank;if(resumable)putSession(s);openSession(s)}
function bankFor(s){if(s.mode==='adaptive'||s.mode==='focused')return s.bank||[];return BANKS[s.mode]||[]}
function openSession(s){show('practice');const qh=document.getElementById('quizHost');qh.classList.remove('hidden');renderQuestion(s)}
function pauseSession(s){putSession(s);document.getElementById('quizHost').classList.add('hidden');renderPractice();alert('Paused and saved. Use Resume on Practice when you are ready.');}
function renderQuestion(s){let bank=bankFor(s),q=bank.find(x=>x.id===s.ids[s.index]);if(!q)return finish(s);let examLike=s.mode==='pretest'||/^week/.test(s.mode),diagnostic=s.mode==='pretest',host=document.getElementById('quizHost'),modeName=diagnostic?'Cold Diagnostic':s.mode==='adaptive'?'Adaptive Practice':s.mode==='focused'?'Focused Practice':s.mode.replace('week','Week ')+' Full Exam';host.innerHTML=`<div class="notice">Autosave ON • resumable${examLike?' • answers hidden until completion':''}${diagnostic?' • mixed questions with no topic labels':''}</div><div class="card questioncard"><div class="enginebar"><div><span class="epill">${modeName}</span>${diagnostic?'<span class="epill">Mixed questions</span>':`<span class="epill">${examLike?'Domain hidden':`D${q.d} • ${D[q.d]}`}</span><span class="epill">${q.difficulty}</span>`}</div><b>Question ${s.index+1} of ${s.ids.length}</b></div><div class="qprogress"><div style="width:${Math.round((s.index)/s.ids.length*100)}%"></div></div><h2>${q.stem}</h2>${q.o.map((o,i)=>`<button class="qoption" data-c="${i}"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}<div class="qcontrols"><div><label>Confidence</label><div class="confidence">${[25,50,75,100].map(v=>`<button data-f="${v}">${v}%</button>`).join('')}</div><label style="display:block;margin-top:14px">Why did you choose it?</label><select id="reasonSel"><option value="">Choose the reasoning that best matches your decision</option>${q.reasonOptions.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select><label style="display:block;margin-top:14px">Optional note</label><textarea id="reasonText" placeholder="Your own reasoning..."></textarea></div><div><label>Eliminate one distractor</label><select id="elim"><option value="">Choose one</option>${q.o.map((_,i)=>`<option value="${i}">${String.fromCharCode(65+i)}</option>`).join('')}</select><div class="tiny" style="margin-top:9px">Cherub scores answer accuracy, confidence calibration, reasoning choice, and whether you correctly eliminated a distractor.</div></div></div><button class="enginebtn secondary" id="pause" style="margin-top:16px">Pause &amp; save</button> <button class="enginebtn" id="submit" style="margin-top:16px">Submit Answer</button><div id="fb"></div></div>`;let c=null,f=null;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{c=+b.dataset.c;document.querySelectorAll('[data-c]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{f=+b.dataset.f;document.querySelectorAll('[data-f]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('pause').onclick=()=>pauseSession(s);document.getElementById('submit').onclick=()=>{if(c===null||f===null)return alert('Choose an answer and confidence first.');submitAnswer(s,q,c,f,examLike)}}
function submitAnswer(s,q,c,f,examLike){let p=load(),elim=document.getElementById('elim').value,rs=document.getElementById('reasonSel').value,a={sessionId:s.id,id:q.id,d:q.d,topic:q.topic,concept:q.concept,relation:q.rel,mistake:q.mistake,choice:c,correctAnswer:q.a,ok:c===q.a,confidence:f,reasoning:document.getElementById('reasonText').value.trim(),reasonChoice:rs===''?null:+rs,reasonCorrect:rs===''?null:+rs===q.reasonAnswer,eliminated:elim===''?null:+elim,eliminationCorrect:elim===''?null:+elim!==q.a,ts:Date.now(),mode:s.mode};p.attempts.push(a);p.questionExposure[q.id]=(p.questionExposure[q.id]||0)+1;save(p);s.index++;if(s.resumable)putSession(s);if(examLike)return renderQuestion(s);document.getElementById('submit').disabled=true;document.querySelectorAll('[data-c],[data-f]').forEach(x=>x.disabled=true);document.getElementById('fb').innerHTML=`<div class="feedbackbox"><b>${a.ok?'Correct':'Not quite'} — best answer ${String.fromCharCode(65+q.a)}</b><p>${q.why}</p><h4>Why each option wins or loses</h4><ol type="A">${q.whyOptions.map(x=>`<li>${x}</li>`).join('')}</ol><p><b>Common trap:</b> ${q.mistake}</p><p><b>Where this fits:</b> ${q.rel}</p><p><b>Reasoning:</b> ${a.reasonCorrect===null?'not selected':a.reasonCorrect?'correct':'needs review'} • <b>Elimination:</b> ${a.eliminationCorrect===null?'not selected':a.eliminationCorrect?'valid':'you eliminated the best answer'}</p><button class="enginebtn secondary" id="openConcept">Open ${q.concept}</button> <button class="enginebtn" id="next">${s.index>=s.ids.length?'Finish':'Next Question'}</button></div>`;document.getElementById('openConcept').onclick=()=>window.dispatchEvent(new CustomEvent('cherub:knowledge',{detail:{domain:`D${q.d}`,concept:q.concept,path:q.rel}}));document.getElementById('next').onclick=()=>renderQuestion(s)}
function finish(s){let p=load(),a=attemptsForSession(s.id,p),correct=a.filter(x=>x.ok).length,rec={id:s.id,mode:s.mode,startedAt:s.startedAt,finishedAt:Date.now(),count:a.length,accuracy:a.length?correct/a.length:0,completed:true};p.sessions.push(rec);if(s.mode==='pretest'){p.completedPretest=true;p.pretestVersion=BASELINE_VERSION}save(p);if(s.resumable)clearSession();document.getElementById('quizHost').classList.add('hidden');renderLocks();renderProgress();show('progress')}
function stats(){let p=load(),all=p.attempts,by={};for(let d=1;d<=4;d++){let a=all.filter(x=>x.d===d);by[d]={n:a.length,acc:a.length?a.filter(x=>x.ok).length/a.length:null}}let acc=all.length?all.filter(x=>x.ok).length/all.length:null,wt=0,u=0;for(let d=1;d<=4;d++)if(by[d].acc!==null){wt+=by[d].acc*W[d];u+=W[d]}wt=u?wt/u:null;let hi=all.filter(x=>x.confidence>=75),reason=all.filter(x=>x.reasonCorrect!==null),elim=all.filter(x=>x.eliminationCorrect!==null);return{p,all,by,acc,score:wt===null?null:Math.round(200+wt*600),cal:hi.length?hi.filter(x=>x.ok).length/hi.length:null,reason:reason.length?reason.filter(x=>x.reasonCorrect).length/reason.length:null,elim:elim.length?elim.filter(x=>x.eliminationCorrect).length/elim.length:null}}
function topicScore(d,t,p){let a=p.attempts.filter(x=>x.d===d&&x.topic===t);return a.length?a.filter(x=>x.ok).length/a.length:null}
function renderDashboard(){let s=stats(),done=s.p.completedPretest,q=document.getElementById('questionsAnswered');if(!q)return;if(!done){q.textContent='N/A';accuracyMetric.textContent='N/A';projectedMetric.textContent='N/A';confidenceMetric.textContent='N/A';readinessScore.textContent='--';readinessStatus.textContent=s.all.length?'Pre-Test In Progress':'Not Started'}else{q.textContent=s.all.length;accuracyMetric.textContent=Math.round((s.acc||0)*100)+'%';projectedMetric.textContent=s.score;confidenceMetric.textContent=s.cal===null?'N/A':Math.round(s.cal*100)+'%';readinessScore.textContent=s.score;readinessStatus.textContent=Object.values(s.by).every(x=>x.acc!==null&&200+x.acc*600>=600)?'Exam-Ready Target':'Building Mastery'}document.querySelectorAll('#domainCards .domain').forEach((card,i)=>{let d=i+1;card.querySelectorAll('.topic').forEach((el,j)=>{let pct=topicScore(d,TOP[d][j],s.p),b=el.querySelector('b'),tr=el.querySelector('.track');b.textContent=!done||pct===null?'--':Math.round(pct*100)+'%';tr.style.background=!done||pct===null?'#e4e9f0':`linear-gradient(90deg,var(--${d===1?'blue':d===2?'green':d===3?'purple':'orange'}) ${Math.round(pct*100)}%,#e4e9f0 ${Math.round(pct*100)}%)`});let btn=card.querySelector('.train');btn.disabled=!done;btn.onclick=()=>start('adaptive')})}
function buildDomains(){const cls={1:'d1',2:'d2',3:'d3',4:'d4'},host=document.getElementById('domainCards');if(!host)return;host.innerHTML=[1,2,3,4].map(d=>`<div class="card domain"><div class="domainhead"><span class="badge ${cls[d]}">D${d}</span><h3>${D[d]}</h3><span class="weight">${Math.round(W[d]*100)}%</span></div>${TOP[d].map(t=>`<div class="topic"><div class="topicline"><span>${t}</span><b>--</b></div><div class="track"></div></div>`).join('')}<button class="train" disabled>◎ &nbsp; Train weakest path<small>Complete pre-test to identify weak areas</small></button></div>`).join('')}
function renderPractice(){let r=getSession(),p=load(),b=document.getElementById('resumeBanner');if(r&&r.bankVersion!==QUESTION_FORMAT_VERSION){clearSession();r=null;}if(b){b.classList.toggle('show',!!r);if(r){resumeText.textContent=`${r.mode} • question ${r.index+1} of ${r.ids.length}`;resumeBtn.onclick=()=>openSession(r)}}renderLocks()}
function renderLocks(){let p=load(),a=document.getElementById('startAdaptive'),e=document.getElementById('startExam');if(a)a.disabled=!p.completedPretest;if(e)e.disabled=!p.completedPretest}
function showExamPicker(){let p=load();if(!p.completedPretest)return alert('Complete the pre-test first.');let host=document.getElementById('quizHost');host.classList.remove('hidden');host.innerHTML=`<div class="card questioncard"><h2>Choose Weekly Full Exam</h2><p>Each exam is a separate fresh 150-question set. You can pause and resume; answers remain hidden until completion.</p><div class="practicegrid">${[3,4,5,6].map(w=>{let done=p.sessions.some(s=>s.mode===`week${w}`&&s.completed);return `<div class="card pcard"><h3>Week ${w}</h3><p>${done?'Completed':'150 questions • pause and resume'}</p><button class="enginebtn" data-week="week${w}" ${done?'disabled':''}>${done?'Completed':'Start Exam'}</button></div>`}).join('')}</div></div>`;document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>start(b.dataset.week))}
function relationMastery(rel,p){let a=p.attempts.filter(x=>x.relation===rel);if(!a.length)return null;let base=a.filter(x=>x.ok).length/a.length,hiWrong=a.filter(x=>!x.ok&&x.confidence===100).length,reason=a.filter(x=>x.reasonCorrect===false).length;return Math.max(0,Math.round(base*100-hiWrong*7-reason*3))}
function renderMap(){let p=load(),el=document.getElementById('mapContent');el.innerHTML=[1,2,3,4].map(d=>`<div class="card progresscard" style="margin-bottom:10px"><b>D${d} ${D[d]}</b><div>${REL[d].map(r=>{let m=relationMastery(r,p);return `<span>${r}${m===null?' • --':` • ${m}%`}</span>`}).join('')}</div></div>`).join('')+`<div class="card progresscard"><b>Core loop</b><div class="mapchain">Business objectives <span>→</span> Governance & authority <span>→</span> Strategy <span>→</span> Risk assessment <span>→</span> Risk decision <span>→</span> Program <span>→</span> Controls <span>→</span> Test/evaluate <span>→</span> Monitor/report <span>→</span> Incident/change <span>→</span> Recover <span>→</span> Lessons learned <span>→</span> Reassess risk</div></div>`}
function renderProgress(){let s=stats(),el=document.getElementById('progressContent');if(!s.p.completedPretest)return el.innerHTML='<section class="notice"><b>Cold diagnostic score is protected.</b><p>Your answers are being saved, but no right/wrong results, topic clues, or scores appear until all 20 questions are submitted.</p></section>';let baseline=s.p.sessions.slice().reverse().find(x=>x.mode==='pretest'&&x.completed),baseAttempts=baseline?attemptsForSession(baseline.id,s.p):[],baseCorrect=baseAttempts.filter(x=>x.ok).length;if(!s.all.length)return el.innerHTML='<p>No attempts yet. Start the cold diagnostic.</p>';let mm={};s.all.filter(x=>!x.ok).forEach(x=>mm[x.mistake]=(mm[x.mistake]||0)+1);let top=Object.entries(mm).sort((a,b)=>b[1]-a[1]).slice(0,10);let hist=s.p.sessions.slice().reverse();el.innerHTML=`<section class="card progresscard"><h2 style="margin-top:0">Your 20-question diagnostic result</h2><div style="font-size:34px;font-weight:800">${baseCorrect} / ${BASELINE_COUNT}</div><p><b>${Math.round(baseCorrect/BASELINE_COUNT*100)}% correct</b> • ${BASELINE_COUNT-baseCorrect} incorrect. Your answers were not revealed during the diagnostic; this result is now available to guide your study.</p></section><div class="progressgrid">${[1,2,3,4].map(d=>`<div class="card progresscard"><b>D${d} ${D[d]}</b><div style="font-size:28px;font-weight:800;margin:8px 0">${s.by[d].acc===null?'--':Math.round(200+s.by[d].acc*600)}</div><div class="tiny">Cherub training score • ${s.by[d].n} attempts</div></div>`).join('')}</div><div class="card progresscard" style="margin-top:12px"><h3>Reasoning diagnostics</h3><p>High-confidence accuracy: ${s.cal===null?'--':Math.round(s.cal*100)+'%'} • Reasoning accuracy: ${s.reason===null?'--':Math.round(s.reason*100)+'%'} • Distractor elimination: ${s.elim===null?'--':Math.round(s.elim*100)+'%'}</p>${top.map(x=>`<span class="epill">${x[0]}: ${x[1]}</span>`).join(' ')||'No misses yet.'}</div><div class="card progresscard" style="margin-top:12px"><b>Overall training readiness:</b> ${s.score??'--'} <span class="tiny">Training score only; not an official ISACA scaled score.</span></div><div class="card progresscard" style="margin-top:12px"><h3>Exam / session history</h3>${hist.length?hist.map(x=>`<div class="topicline"><span>${x.mode} • ${new Date(x.finishedAt).toLocaleDateString()}</span><b>${Math.round(x.accuracy*100)}%</b></div>`).join(''):'No completed sessions yet.'}</div>`}
function renderSchedule(){let p=load(),el=document.querySelector('#schedule .placeholder');if(!el)return;const done=m=>p.sessions.some(s=>s.mode===m&&s.completed);el.innerHTML=`<h1>Schedule</h1><p>Six-week progression. The diagnostic drives adaptive work; weekly full exams are fresh independent checks that can pause and resume.</p><div class="progressgrid">${[['Week 1','Cold 20-question diagnostic','pretest',p.completedPretest],['Week 2','Adaptive Hard/Harder every 2–3 days','adaptive',p.sessions.some(s=>s.mode==='adaptive')],['Week 3','Fresh 150Q Full Exam','week3',done('week3')],['Week 4','Fresh 150Q Full Exam','week4',done('week4')],['Week 5','Fresh 150Q Full Exam','week5',done('week5')],['Week 6','Fresh 150Q Full Exam','week6',done('week6')]].map(x=>`<div class="card progresscard"><b>${x[0]}</b><p>${x[1]}</p><span class="epill">${x[3]?'Completed':'Pending'}</span>${x[2]==='adaptive'&&p.completedPretest?'<button class="enginebtn" data-go="adaptive">Practice</button>':''}${/^week/.test(x[2])&&p.completedPretest&&!x[3]?`<button class="enginebtn" data-go="${x[2]}">Start</button>`:''}</div>`).join('')}</div>`;el.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>start(b.dataset.go))}
function renderNotes(){let el=document.querySelector('#notes .placeholder'),v=localStorage.getItem(NK)||'';el.innerHTML=`<h1>Notes</h1><p>Private notes stored in this browser.</p><textarea id="notesBox" style="width:100%;min-height:360px;border:1px solid #d4deeb;border-radius:10px;padding:12px">${v.replace(/</g,'&lt;')}</textarea><p><button class="enginebtn" id="saveNotes">Save Notes</button></p>`;saveNotes.onclick=()=>{localStorage.setItem(NK,notesBox.value);alert('Notes saved.')};}
function renderResources(){let el=document.querySelector('#resources .placeholder');el.innerHTML=`<h1>Resources</h1><div class="card progresscard"><h3>Current exam boundary</h3><p>D1 17% • D2 20% • D3 33% • D4 30%.</p></div><div class="card progresscard" style="margin-top:12px"><h3>Cherub source model</h3><p>Index → referenced locations → domain sections → tables/figures → glossary/acronyms → observed relationship → question.</p><p>The repository stores transformed study data and original Cherub questions, not licensed manual pages or recordings.</p></div>`}
function exportProgress(){let p=load(),blob=new Blob([JSON.stringify({appVersion:M.appVersion,exported:new Date().toISOString(),progress:p,notes:localStorage.getItem(NK)||''},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cherub-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importFile(file){let fr=new FileReader();fr.onload=()=>{try{let x=JSON.parse(fr.result),p=x.progress||x.data||x;if(!p.attempts)throw Error();localStorage.setItem(PK,JSON.stringify({...base(),...p}));if(typeof x.notes==='string')localStorage.setItem(NK,x.notes);clearSession();renderDashboard();renderLocks();alert('Backup imported.')}catch{alert('That file is not a valid Cherub backup.')}};fr.readAsText(file)}
function renderSettings(){let el=document.querySelector('#settings .placeholder'),p=load();el.innerHTML=`<h1>Settings</h1><div class="card progresscard"><h3>Application</h3><p>Version <b>${M.appVersion}</b></p><p>Progress is autosaved locally after every submitted answer. App/content updates are separate from your progress.</p></div><div class="card progresscard" style="margin-top:12px"><h3>Backup & restore</h3><button class="enginebtn" id="sx">Export Backup</button> <button class="enginebtn secondary" id="si">Import Backup</button><input id="sf" type="file" accept="application/json" class="hidden"></div><div class="card progresscard" style="margin-top:12px"><h3>Reset</h3><button class="enginebtn secondary" id="resetAll">Reset All Local Progress</button></div>`;sx.onclick=exportProgress;si.onclick=()=>sf.click();sf.onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);resetAll.onclick=()=>{if(confirm('Reset ALL Cherub progress and notes on this browser?')){localStorage.removeItem(PK);localStorage.removeItem(SK);localStorage.removeItem(NK);renderDashboard();renderLocks();show('dashboard')}}}
function wire(){buildDomains();startPretest.onclick=()=>start('pretest');startAdaptive.onclick=()=>start('adaptive');startExam.onclick=showExamPicker;exportProgress.onclick=exportProgress;importProgress.onclick=()=>importFile.click();importFile.onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);renderDashboard();renderPractice();renderSchedule();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
