'use strict';
(()=>{
const M=window.CHERUB_MANIFEST||{appVersion:'2026.09.10.4'};
const PK='cherub.progress.v7',SK='cherub.session.v7',NK='cherub.notes.v1';
const D={1:'Information Security Governance',2:'Information Risk Management',3:'Information Security Program Development',4:'Information Security Incident Management'};
const W={1:.17,2:.20,3:.33,4:.30},N={1:26,2:30,3:49,4:45};
const TOP={1:['Business alignment','Governance / authority','Roles & accountability','Strategy'],2:['Risk assessment','Risk response','Residual risk / ownership','Monitoring / reporting'],3:['Program development','Control design / selection','Implementation','Testing / effectiveness'],4:['Readiness / planning','Investigation / classification','Containment decisions','Recovery']};
const REL={1:['Business objectives → security strategy','Governance → decision rights','Risk appetite → tolerance','Business owner → risk acceptance','Metrics → executive decisions'],2:['Threat/vulnerability → risk assessment','Controls → residual risk','Residual risk → risk owner','Treatment → monitoring','Material change → reassessment'],3:['Requirements → program objectives','Program → control design','Implementation → operation','Operation → testing','Testing → effectiveness','Effectiveness → metrics'],4:['BIA → RTO/RPO','RTO/RPO → recovery strategy','Plan → recovery test','Incident → classify/triage','Contain → eradicate → recover','Post-incident review → corrective action']};
const RULES={
1:[
['Business alignment',0,'Map security priorities to business objectives, enterprise risk, and accountable decision rights.','Prioritize the technical solution with the broadest coverage','Map the decision to business objectives, risk appetite, and accountable ownership','Let security accept the business risk','Delay until every policy and standard is perfect','business-alignment'],
['Risk ownership',2,'Material business risk is accepted by the accountable business owner; security advises.','Ask internal audit to accept the risk','Have the security manager accept it','Present risk and treatment choices to the accountable business owner','Transfer ownership to the technology vendor','wrong-owner'],
['Risk appetite',1,'Translate appetite into measurable tolerance and decision thresholds before changing controls.','Increase every security control immediately','Translate appetite into tolerances, thresholds, and prioritized gaps','Wait for the next annual audit','Use vulnerability severity as the enterprise risk threshold','appetite-vs-tolerance'],
['Governance metrics',0,'Use outcome metrics tied to business risk and objectives rather than activity counts.','Report number of alerts processed','Report number of security tools deployed','Report reduction in business-impacting risk against approved targets','Report number of awareness emails sent','activity-vs-outcome'],
['Decision authority',1,'Define who can make material risk decisions and how escalation works.','Give all analysts authority to stop business services','Define decision rights and escalation thresholds','Move all decisions to internal audit','Require unanimous technical-team approval','authority'],
['Compliance scope',3,'Determine applicability and affected business scope before choosing controls.','Apply every new requirement enterprise-wide immediately','Determine applicability, obligations, and affected assets first','Ask a vendor to define the legal scope','Treat compliance as identical to risk','compliance-vs-risk'],
['Business case',3,'Compare investments using risk reduction, obligations, dependencies, and strategic value.','Choose the lowest-cost control','Choose the highest-rated vendor','Compare expected risk reduction and strategic value','Choose the project with the most technical features','business-value'],
['Policy governance',1,'Policy exceptions should be governed, time-bound, risk-based, and owned.','Ban all exceptions','Approve permanent exceptions informally','Use a documented, risk-based, time-bound exception with accountable approval','Let administrators approve their own exceptions','exception-governance'],
['Board reporting',0,'Executives need decision-oriented information in business terms.','Provide raw event logs','Present business impact, trend, options, and decisions required','Send only vulnerability counts','Report every technical issue at equal priority','executive-reporting'],
['M&A governance',3,'Assess equivalence and risk before replacing an acquired company’s controls.','Replace every acquired control immediately','Assess objectives, mandatory requirements, and control equivalence first','Let the acquired company remain permanently independent','Ask audit to operate the integration','assessment-before-action']],
2:[
['Risk assessment',0,'Assess likelihood and business impact in the current control environment before treatment.','Remediate every vulnerability immediately','Assess likelihood, impact, exposure, and existing controls first','Accept the risk before analysis','Use the vulnerability score as the risk decision','assessment-before-treatment'],
['Risk criteria',0,'Use common scales and impact guidance tied to business objectives.','Always use the highest rating','Define common criteria, scales, and business impact guidance','Average conflicting ratings without analysis','Let security assign every business impact','risk-criteria'],
['Third-party risk',0,'Evaluate legal, contractual, resilience, control, and data-handling risk against enterprise requirements.','Rely on vendor marketing material','Assess the provider against enterprise risk and compliance requirements','Require identical tools to your environment','Treat one penetration test as sufficient','third-party-assurance'],
['Risk treatment',1,'Present viable treatment options and support an informed owner decision.','Implement the most expensive control','Validate analysis and present treatment options to the accountable owner','Delete the risk if the owner rejects a control','Have audit choose the treatment','wrong-owner'],
['Residual risk',2,'Residual risk reflects the likelihood and impact remaining after effective controls.','Set residual risk to zero when any control exists','Reassess likelihood and impact based on actual control effectiveness','Reduce likelihood and impact by the same amount automatically','Ignore compensating controls','implemented-vs-effective'],
['Risk register',3,'A useful register prioritizes decisions, ownership, thresholds, and treatment status.','Sort risks alphabetically','Prioritize by impact, likelihood, ownership, treatment status, and tolerance','Add every vulnerability as a separate executive risk','Hide accepted risks','risk-reporting'],
['Risk escalation',1,'Risks above tolerance require explicit escalation and accountable decisions.','Lower the rating until treatment is available','Escalate with interim options and explicit decision requirements','Assume management accepts the risk','Remove the risk from reporting','risk-escalation'],
['Risk monitoring',3,'Reassess when assets, threats, controls, impact, or assumptions materially change.','Assess only once per year regardless of change','Refresh assessment after significant change and monitor key indicators','Replace monitoring with audits','Keep ratings fixed for trend consistency','change-reassessment'],
['Risk reporting',3,'Aggregated risk needs methodology, uncertainty, drivers, and drill-down.','Give one number without assumptions','Provide aggregation with assumptions, uncertainty, and material drivers','Refuse to summarize risk','Use the highest CVSS score as enterprise risk','risk-reporting'],
['Cloud assurance',0,'Determine whether available independent assurance is sufficient for your obligations and risk.','Reject any provider without custom audit rights','Assess whether available assurance satisfies specific requirements','Accept any famous cloud provider automatically','Perform unauthorized testing','assurance-sufficiency']],
3:[
['Program alignment',0,'Program capabilities should trace to business requirements, risks, obligations, and priorities.','Buy a larger SIEM first','Map program objectives and capabilities to business and risk requirements','Add controls until every framework item is covered','Let technical teams set priorities independently','program-alignment'],
['Control effectiveness',3,'Measure whether controls change relevant risk outcomes, not merely whether they are installed.','Count implemented controls only','Measure control effectiveness against intended risk outcomes','Use vendor certifications as proof of effectiveness','Increase tool count','implemented-vs-effective'],
['Control lifecycle',2,'A control needs ownership, operation, monitoring, support, and maintenance before rollout.','Deploy once technical testing passes','Resolve ownership, support, monitoring, and lifecycle requirements','Assign control operation to audit','Ignore operations concerns','control-lifecycle'],
['Security architecture',0,'Architecture translates requirements into coherent principles and target capabilities.','Document product versions only','Translate business and security requirements into design principles and capabilities','Replace risk management with architecture','Make every system identical','architecture-alignment'],
['Awareness effectiveness',3,'Measure behavior and risk outcomes rather than attendance or activity volume.','Count training slides','Measure observed behavior change and reporting outcomes','Count reminder emails','Use attendance as the sole metric','activity-vs-outcome'],
['Roadmap prioritization',0,'Prioritize by business risk reduction, obligations, dependencies, and strategic value.','Choose whichever vendor offers a discount','Prioritize by risk reduction, obligations, dependencies, and strategic value','Fund teams in alphabetical order','Prioritize by complaint volume','business-value'],
['Standards',1,'Use enterprise control objectives and minimum requirements with governed exceptions.','Mandate one vendor for every control','Define enterprise minimum requirements and governed exceptions','Rely on audits to define standards','Let each business unit define unrelated objectives','policy-vs-standard'],
['Key-person risk',0,'Build sustainable capability with documentation, cross-training, and succession.','Give the expert permanent exception authority','Reduce concentration risk through documentation and cross-training','Outsource immediately without analysis','Accept the dependency because performance is good','resource-risk'],
['Requirements',0,'Security should define requirements and advise; accountable business owners retain risk decisions.','Security should own project business risk','Provide requirements and risk advice to the accountable owner','Security should guarantee zero breach risk','Have audit approve the technical design','wrong-owner'],
['Resource management',0,'Program resources should be allocated according to risk, business value, and critical dependencies.','Allocate evenly to every request','Allocate based on prioritized risk and business value','Fund only the newest technologies','Let vendors decide the roadmap','business-value'],
['Change integration',2,'Security requirements should be embedded in business and technology change processes.','Review security only after deployment','Integrate security requirements early in the change lifecycle','Block all change until annual review','Delegate every security decision to developers','security-by-design'],
['Control exceptions',1,'Exceptions should preserve the control objective through compensating measures and accountable approval.','Ignore exceptions once approved','Use risk-based approval, compensating controls, and expiry','Make exceptions permanent','Let requestors self-approve','exception-governance'],
['Program metrics',3,'Use leading and lagging measures tied to objectives and risk outcomes.','Report activity counts only','Use measures that show capability, outcomes, and business risk trend','Use one metric for all stakeholders','Avoid trend data','activity-vs-outcome'],
['Vendor integration',2,'Third-party services need clear requirements, ownership, monitoring, and exit considerations.','Treat signed contracts as sufficient','Define security requirements, monitoring, ownership, and exit needs','Let procurement own all cyber risk','Skip monitoring after onboarding','third-party-assurance'],
['Data protection',1,'Controls should follow data classification, business use, legal obligations, and risk.','Encrypt everything identically without context','Apply protection based on classification, obligations, and business risk','Let users choose controls individually','Use retention as the only protection decision','classification-driven-controls'],
['Resilience',0,'Program design should account for continuity, dependencies, recovery objectives, and failure modes.','Focus only on prevention','Design for resilience, recovery objectives, and critical dependencies','Assume high availability equals resilience','Make security own all business continuity decisions','resilience']],
4:[
['Incident activation',1,'Activate the process, establish scope/severity, roles, coordination, and decision authority first.','Immediately rebuild every affected system','Activate the incident process and establish scope, severity, roles, and coordination','Notify the media first','Delete suspicious files','scenario-state'],
['Containment authority',2,'Material containment decisions need predefined business/incident authority and escalation.','Let the fastest analyst decide','Use predefined accountable authority and escalation for business-impacting containment','Let the vendor decide','Wait for internal audit','authority'],
['Classification',1,'Classification enables consistent prioritization, escalation, response, and communication.','Use classification only for reporting style','Classify to drive prioritization, escalation, response, and communication','Replace root-cause analysis with classification','Eliminate professional judgment','classification'],
['Notification',1,'Potential notification obligations should trigger legal/privacy coordination early while facts and timelines are preserved.','Notify every regulator immediately','Engage legal/privacy decision processes early and preserve facts/timelines','Wait until all technical investigation is complete','Ask the attacker for confirmation','notification-sequence'],
['Eradication and recovery',3,'Validate eradication and recovery criteria before controlled restoration.','Restore immediately after containment','Validate eradication and recovery criteria before controlled restoration','Close the incident after containment','Stop monitoring during recovery','scenario-state'],
['Lessons learned',3,'Address technical and nontechnical causes, business/process/control issues, and accountable corrective actions.','Document malware details only','Identify technical and business/process/control causes with accountable corrective actions','Close once systems are restored','Leave actions unassigned','post-incident-improvement'],
['Exercises',0,'Exercises should validate decision rights, dependencies, communications, procedures, and recovery assumptions.','Measure exercise success by attendance','Use exercises to validate roles, authority, dependencies, and procedures','Run the same scenario without remediation','Limit exercises to SOC analysts','evidence-vs-documentation'],
['Evidence handling',1,'Preserve integrity, provenance, chronology, and legal requirements while supporting response.','Delete artifacts after imaging','Preserve evidence integrity, chronology, and handling requirements','Let every responder copy evidence freely','Prioritize convenience over provenance','evidence-handling'],
['Recovery validation',3,'Recovery points and systems must be trustworthy and monitored so compromise is not reintroduced.','Restore the newest backup without checking it','Validate the recovery source and monitor restoration for recurrence','Delete all backups after an incident','Ask audit to perform restoration','recovery-validation'],
['IR metrics',3,'Measure detection, escalation, containment, recovery, communication, and corrective-action closure.','Count pages in the response plan','Measure response outcomes and closure of corrective actions','Count tools in the SOC','Use incident labels as the main success metric','activity-vs-outcome'],
['Crisis communication',2,'Use predefined, authorized communication channels and coordinated messaging.','Allow any responder to speak publicly','Use authorized communication roles and coordinated messaging','Delay all internal communication until closure','Let vendors issue statements for the organization','authority'],
['Incident ownership',2,'Technical responders execute tasks, while accountable incident/business leadership owns material decisions.','Make analysts own all business risk','Separate technical execution from accountable material decision authority','Let audit command the incident','Let legal run technical containment','wrong-owner'],
['Detection escalation',1,'Alert severity alone is insufficient; escalation should reflect business context and incident criteria.','Escalate only by tool severity','Use validated incident criteria and business impact to drive escalation','Escalate every alert to executives','Ignore low-severity alerts permanently','technical-vs-business'],
['Post-incident improvement',3,'Lessons learned should feed program, control, architecture, training, and governance improvements.','Archive the report and make no changes','Track corrective actions into program and control improvements','Only update the incident plan','Treat each incident as isolated','post-incident-improvement'],
['Playbooks',0,'Playbooks should guide repeatable action while preserving decision points and escalation.','Make playbooks fully automatic for all business decisions','Use playbooks for repeatable actions with explicit decision and escalation points','Avoid playbooks because incidents differ','Let each responder improvise without common steps','authority']]
};
const ORGS=['global manufacturer','regional bank','healthcare provider','cloud software company','government contractor','online retailer','university','insurance company','logistics company','financial services firm','research organization','energy company'];
const TRIG=['after a major acquisition','during a cloud migration','before a critical product launch','after an audit finding','while budgets are constrained','after a regulatory change','during an executive review','after repeated control failures','during third-party onboarding','after a significant incident','while modernizing legacy systems','during annual planning'];
const STATES=['The organization has incomplete decision evidence','Management has asked for a recommendation','A business owner is awaiting a decision','Technical teams have proposed an immediate fix','Existing controls are operating but their effectiveness is uncertain','The situation has changed since the last assessment'];
const SCENARIOS={
1:['The board is reviewing a growth plan and wants to know which security decisions require executive ownership.','A business unit requests an exception that could affect a material customer commitment.','An acquisition introduces conflicting policies, decision rights, and reporting practices.','Leadership sees many security activity metrics but cannot see whether business risk is improving.','A new regulatory obligation affects only part of the enterprise and its shared services.'],
2:['A critical supplier changes its hosting model after the annual risk assessment was completed.','A high-value process has several vulnerabilities, but existing controls may already reduce the exposure.','A business leader wants to accept a risk while the technical team recommends a costly control.','A risk register shows many issues but does not distinguish material decisions from technical findings.','A new threat report conflicts with prior impact assumptions for a customer-facing service.'],
3:['A transformation program is selecting controls before the target business requirements are fully agreed.','A control has been deployed, but operations cannot show ownership, evidence, or a monitoring plan.','A vendor service is being onboarded quickly and lacks clear security exit and assurance requirements.','Training attendance is high, but unsafe behavior and late incident reporting continue.','A program dashboard reports tool deployment and ticket volume but not risk-reduction outcomes.'],
4:['A ransomware event disrupts a critical service while executives debate whether to disconnect a shared platform.','A suspected incident may trigger notification obligations, but facts and the timeline are still developing.','Recovery teams want to restore immediately although the trusted recovery point is not validated.','An exercise revealed unclear authority, stale contacts, and dependencies not reflected in the plan.','A post-incident report identifies recurring failures, but corrective actions have no owner or due date.']
};
function prng(seed){let x=seed>>>0;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296)}
function shuffle(a,r=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function whyWrong(t){let s=t.toLowerCase();if(s.includes('audit'))return 'Audit provides independent assurance; it normally does not own the business decision or operate the control.';if(s.includes('vendor'))return 'A vendor can support execution, but accountability and enterprise risk decisions remain with the organization.';if(s.includes('immediately')||s.includes('first'))return 'This acts before the required management context, authority, or evidence is established.';if(s.includes('every')||s.includes('all '))return 'This is overly absolute and ignores risk, scope, business context, or proportionality.';if(s.includes('wait')||s.includes('delay'))return 'This delays a decision that should be governed through defined authority and risk-based action.';return 'This may be reasonable in another context, but it does not best satisfy the management objective, sequence, or accountable decision required here.'}
function makeQ(d,i,seed,label){const r=prng(seed*1000+d*100+i),rule=RULES[d][(i+seed)%RULES[d].length],base=[rule[3],rule[4],rule[5],rule[6]],rot=(i+seed)%4,order=[0,1,2,3].map(x=>(x+rot)%4),o=order.map(x=>base[x]),a=o.indexOf(rule[4]),qual=(i+seed)%3===0?'FIRST':'BEST',org=ORGS[Math.floor(r()*ORGS.length)],tr=TRIG[Math.floor(r()*TRIG.length)],st=STATES[Math.floor(r()*STATES.length)],frame=SCENARIOS[d][(i+seed)%SCENARIOS[d].length],rels=REL[d];const correctReason=rule[2];const rr=shuffle([correctReason,`Choose the option with the strongest technical capability regardless of business ownership.`,`Escalate the matter before establishing whether the defined decision threshold is met.`,`Treat documented implementation as sufficient evidence that the intended risk outcome is achieved.`],r);return{id:`${label}-D${d}-${String(i+1).padStart(3,'0')}`,d,topic:TOP[d][rule[1]],concept:rule[0],mistake:rule[7],rel:rels[(i+seed)%rels.length],difficulty:(i+seed)%5===0?'Very Hard':(i+seed)%2?'Hard':'Harder',scenarioFamily:frame,stem:`A ${org} ${tr}. ${frame} ${st}. A decision involving ${rule[0].toLowerCase()} is required. What should the information security manager do ${qual}?`,o,a,why:rule[2],whyOptions:o.map((x,j)=>j===a?rule[2]:whyWrong(x)),reasonOptions:rr,reasonAnswer:rr.indexOf(correctReason),qualifier:qual};}
function makeBank(seed,label){let out=[];for(let d=1;d<=4;d++)for(let i=0;i<N[d];i++)out.push(makeQ(d,i,seed,label));return shuffle(out,prng(seed+77));}
const BANKS={pretest:makeBank(101,'PRE'),week3:makeBank(303,'W3'),week4:makeBank(404,'W4'),week5:makeBank(505,'W5'),week6:makeBank(606,'W6')};
const base=()=>({schema:7,completedPretest:false,attempts:[],sessions:[],questionExposure:{},relationshipMastery:{},settings:{autoUpdate:true},updatedAt:Date.now()});
const load=()=>{try{return {...base(),...JSON.parse(localStorage.getItem(PK)||'{}')}}catch{return base()}};
const save=p=>{p.updatedAt=Date.now();localStorage.setItem(PK,JSON.stringify(p));renderDashboard();renderSchedule();};
const getSession=()=>{try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}};
const putSession=s=>localStorage.setItem(SK,JSON.stringify(s));
const clearSession=()=>localStorage.removeItem(SK);
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.menu button').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelector(`[data-v="${id}"]`)?.classList.add('active');if(id==='progress')renderProgress();if(id==='map')renderMap();if(id==='practice')renderPractice();if(id==='schedule')renderSchedule();if(id==='notes')renderNotes();if(id==='resources')renderResources();if(id==='settings')renderSettings();}window.show=show;
function attemptsForSession(id,p=load()){return p.attempts.filter(a=>a.sessionId===id)}
function weakDomains(p=load()){return [1,2,3,4].map(d=>{let a=p.attempts.filter(x=>x.d===d);return[d,a.length?a.filter(x=>x.ok).length/a.length:0]}).sort((a,b)=>a[1]-b[1]).map(x=>x[0])}
function makeAdaptive(){let p=load(),quota=[8,5,4,3],order=weakDomains(p),seed=Math.floor(Date.now()/86400000),pool=[];order.forEach((d,k)=>{for(let i=0;i<quota[k];i++)pool.push(makeQ(d,i+seed%37,700+seed+k,'ADP'))});return shuffle(pool,prng(seed));}
function start(mode){let p=load();if(mode!=='pretest'&&!p.completedPretest)return alert('Complete the 150-question cold pre-test first.');if(mode==='pretest'){let old=getSession();if(old&&old.mode==='pretest')return openSession(old);return createSession('pretest',BANKS.pretest,true)}if(mode==='adaptive')return createSession('adaptive',makeAdaptive(),true);if(/^week[3-6]$/.test(mode)){if(p.sessions.some(s=>s.mode===mode&&s.completed))return alert('That weekly full exam is already completed.');if(!confirm('This is a 150-question full exam. You may pause and resume it; answers remain hidden until completion. Start now?'))return;return createSession(mode,BANKS[mode],true)}}
function focusRuleIndices(d,focus){let words=String(focus||'').toLowerCase().match(/[a-z]{3,}/g)||[],scored=RULES[d].map((r,i)=>[i,words.reduce((n,w)=>n+(r.slice(0,3).join(' ').toLowerCase().includes(w)?1:0),0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);return scored.length?scored:[...RULES[d].keys()]}
function challengeContext(level){if(level<=7)return 'The decision scope and accountable owner are clear.';if(level<=14)return 'Two stakeholders disagree about timing, and the available evidence is incomplete.';return 'The business deadline is fixed, a third party is involved, competing risk objectives exist, and leadership needs an accountable recommendation with an interim option.'}
function startFocused(c){let p=load();if(!p.completedPretest)return alert('Complete the 150-question cold pre-test first.');let d=Math.max(1,Math.min(4,+c.domain||1)),count=Math.max(5,Math.min(150,+c.count||10)),level=Math.max(1,Math.min(20,+c.level||10)),seed=Date.now()%100000,focus=c.concept||c.path||TOP[d][0],selected=focusRuleIndices(d,focus),pool=[];for(let i=0;i<Math.max(count*3,30);i++){let sourceIndex=selected[i%selected.length],q=makeQ(d,sourceIndex+i*RULES[d].length,900+level,`FOCUS-${d}`);q.focus=focus;q.concept=focus;q.rel=c.path||q.rel;q.level=Math.max(1,Math.min(20,level+((i%5)-2)));q.difficulty=q.level<=7?`Foundation ${q.level}/20`:q.level<=14?`Hard ${q.level}/20`:`Hardest ${q.level}/20`;q.stem=q.stem.replace('A decision involving '+RULES[d][sourceIndex][0].toLowerCase(),`A decision involving ${focus.toLowerCase()}`)+` ${challengeContext(q.level)}`;q.why=`For ${focus}, ${q.why.charAt(0).toLowerCase()+q.why.slice(1)}`;pool.push(q)}pool.sort((a,b)=>Math.abs(a.level-level)-Math.abs(b.level-level));createSession('focused',pool.slice(0,count),true)}window.CherubStartFocused=startFocused;
function createSession(mode,bank,resumable){let ids=Array.isArray(bank)?bank.map(x=>x.id):bank.ids,s={id:`${mode}-${Date.now()}`,mode,index:0,ids,startedAt:Date.now(),resumable};if(mode==='adaptive')window.__adaptive=bank;if(mode==='focused')s.bank=bank;if(resumable)putSession(s);openSession(s)}
function bankFor(s){if(s.mode==='adaptive')return window.__adaptive||makeAdaptive();if(s.mode==='focused')return s.bank||[];return BANKS[s.mode]||[]}
function openSession(s){show('practice');const qh=document.getElementById('quizHost');qh.classList.remove('hidden');renderQuestion(s)}
function pauseSession(s){putSession(s);document.getElementById('quizHost').classList.add('hidden');renderPractice();alert('Paused and saved. Use Resume on Practice when you are ready.');}
function renderQuestion(s){let bank=bankFor(s),q=bank.find(x=>x.id===s.ids[s.index]);if(!q)return finish(s);let examLike=s.mode==='pretest'||/^week/.test(s.mode),host=document.getElementById('quizHost'),modeName=s.mode==='pretest'?'Cold Pre-Test':s.mode==='adaptive'?'Adaptive Practice':s.mode.replace('week','Week ')+' Full Exam';host.innerHTML=`<div class="notice">Autosave ON • resumable${examLike?' • answers hidden until completion':''}</div><div class="card questioncard"><div class="enginebar"><div><span class="epill">${modeName}</span><span class="epill">${examLike?'Domain hidden':`D${q.d} • ${D[q.d]}`}</span><span class="epill">${q.difficulty}</span></div><b>${s.index+1} / ${s.ids.length}</b></div><div class="qprogress"><div style="width:${Math.round((s.index)/s.ids.length*100)}%"></div></div><h2>${q.stem}</h2>${q.o.map((o,i)=>`<button class="qoption" data-c="${i}"><b>${String.fromCharCode(65+i)}.</b> ${o}</button>`).join('')}<div class="qcontrols"><div><label>Confidence</label><div class="confidence">${[25,50,75,100].map(v=>`<button data-f="${v}">${v}%</button>`).join('')}</div><label style="display:block;margin-top:14px">Why did you choose it?</label><select id="reasonSel"><option value="">Choose the reasoning that best matches your decision</option>${q.reasonOptions.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select><label style="display:block;margin-top:14px">Optional note</label><textarea id="reasonText" placeholder="Your own reasoning..."></textarea></div><div><label>Eliminate one distractor</label><select id="elim"><option value="">Choose one</option>${q.o.map((_,i)=>`<option value="${i}">${String.fromCharCode(65+i)}</option>`).join('')}</select><div class="tiny" style="margin-top:9px">Cherub scores answer accuracy, confidence calibration, reasoning choice, and whether you correctly eliminated a distractor.</div></div></div><button class="enginebtn secondary" id="pause" style="margin-top:16px">Pause &amp; save</button> <button class="enginebtn" id="submit" style="margin-top:16px">Submit Answer</button><div id="fb"></div></div>`;let c=null,f=null;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{c=+b.dataset.c;document.querySelectorAll('[data-c]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{f=+b.dataset.f;document.querySelectorAll('[data-f]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('pause').onclick=()=>pauseSession(s);document.getElementById('submit').onclick=()=>{if(c===null||f===null)return alert('Choose an answer and confidence first.');submitAnswer(s,q,c,f,examLike)}}
function submitAnswer(s,q,c,f,examLike){let p=load(),elim=document.getElementById('elim').value,rs=document.getElementById('reasonSel').value,a={sessionId:s.id,id:q.id,d:q.d,topic:q.topic,concept:q.concept,relation:q.rel,mistake:q.mistake,choice:c,correctAnswer:q.a,ok:c===q.a,confidence:f,reasoning:document.getElementById('reasonText').value.trim(),reasonChoice:rs===''?null:+rs,reasonCorrect:rs===''?null:+rs===q.reasonAnswer,eliminated:elim===''?null:+elim,eliminationCorrect:elim===''?null:+elim!==q.a,ts:Date.now(),mode:s.mode};p.attempts.push(a);p.questionExposure[q.id]=(p.questionExposure[q.id]||0)+1;save(p);s.index++;if(s.resumable)putSession(s);if(examLike)return renderQuestion(s);document.getElementById('submit').disabled=true;document.querySelectorAll('[data-c],[data-f]').forEach(x=>x.disabled=true);document.getElementById('fb').innerHTML=`<div class="feedbackbox"><b>${a.ok?'Correct':'Not quite'} — best answer ${String.fromCharCode(65+q.a)}</b><p>${q.why}</p><h4>Why each option wins or loses</h4><ol type="A">${q.whyOptions.map(x=>`<li>${x}</li>`).join('')}</ol><p><b>Common trap:</b> ${q.mistake}</p><p><b>Where this fits:</b> ${q.rel}</p><p><b>Reasoning:</b> ${a.reasonCorrect===null?'not selected':a.reasonCorrect?'correct':'needs review'} • <b>Elimination:</b> ${a.eliminationCorrect===null?'not selected':a.eliminationCorrect?'valid':'you eliminated the best answer'}</p><button class="enginebtn secondary" id="openConcept">Open ${q.concept}</button> <button class="enginebtn" id="next">${s.index>=s.ids.length?'Finish':'Next Question'}</button></div>`;document.getElementById('openConcept').onclick=()=>window.dispatchEvent(new CustomEvent('cherub:knowledge',{detail:{domain:`D${q.d}`,concept:q.concept,path:q.rel}}));document.getElementById('next').onclick=()=>renderQuestion(s)}
function finish(s){let p=load(),a=attemptsForSession(s.id,p),correct=a.filter(x=>x.ok).length,rec={id:s.id,mode:s.mode,startedAt:s.startedAt,finishedAt:Date.now(),count:a.length,accuracy:a.length?correct/a.length:0,completed:true};p.sessions.push(rec);if(s.mode==='pretest')p.completedPretest=true;save(p);if(s.resumable)clearSession();document.getElementById('quizHost').classList.add('hidden');renderLocks();renderProgress();show('progress')}
function stats(){let p=load(),all=p.attempts,by={};for(let d=1;d<=4;d++){let a=all.filter(x=>x.d===d);by[d]={n:a.length,acc:a.length?a.filter(x=>x.ok).length/a.length:null}}let acc=all.length?all.filter(x=>x.ok).length/all.length:null,wt=0,u=0;for(let d=1;d<=4;d++)if(by[d].acc!==null){wt+=by[d].acc*W[d];u+=W[d]}wt=u?wt/u:null;let hi=all.filter(x=>x.confidence>=75),reason=all.filter(x=>x.reasonCorrect!==null),elim=all.filter(x=>x.eliminationCorrect!==null);return{p,all,by,acc,score:wt===null?null:Math.round(200+wt*600),cal:hi.length?hi.filter(x=>x.ok).length/hi.length:null,reason:reason.length?reason.filter(x=>x.reasonCorrect).length/reason.length:null,elim:elim.length?elim.filter(x=>x.eliminationCorrect).length/elim.length:null}}
function topicScore(d,t,p){let a=p.attempts.filter(x=>x.d===d&&x.topic===t);return a.length?a.filter(x=>x.ok).length/a.length:null}
function renderDashboard(){let s=stats(),done=s.p.completedPretest,q=document.getElementById('questionsAnswered');if(!q)return;if(!done){q.textContent='N/A';accuracyMetric.textContent='N/A';projectedMetric.textContent='N/A';confidenceMetric.textContent='N/A';readinessScore.textContent='--';readinessStatus.textContent=s.all.length?'Pre-Test In Progress':'Not Started'}else{q.textContent=s.all.length;accuracyMetric.textContent=Math.round((s.acc||0)*100)+'%';projectedMetric.textContent=s.score;confidenceMetric.textContent=s.cal===null?'N/A':Math.round(s.cal*100)+'%';readinessScore.textContent=s.score;readinessStatus.textContent=Object.values(s.by).every(x=>x.acc!==null&&200+x.acc*600>=600)?'Exam-Ready Target':'Building Mastery'}document.querySelectorAll('#domainCards .domain').forEach((card,i)=>{let d=i+1;card.querySelectorAll('.topic').forEach((el,j)=>{let pct=topicScore(d,TOP[d][j],s.p),b=el.querySelector('b'),tr=el.querySelector('.track');b.textContent=!done||pct===null?'--':Math.round(pct*100)+'%';tr.style.background=!done||pct===null?'#e4e9f0':`linear-gradient(90deg,var(--${d===1?'blue':d===2?'green':d===3?'purple':'orange'}) ${Math.round(pct*100)}%,#e4e9f0 ${Math.round(pct*100)}%)`});let btn=card.querySelector('.train');btn.disabled=!done;btn.onclick=()=>start('adaptive')})}
function buildDomains(){const cls={1:'d1',2:'d2',3:'d3',4:'d4'},host=document.getElementById('domainCards');if(!host)return;host.innerHTML=[1,2,3,4].map(d=>`<div class="card domain"><div class="domainhead"><span class="badge ${cls[d]}">D${d}</span><h3>${D[d]}</h3><span class="weight">${Math.round(W[d]*100)}%</span></div>${TOP[d].map(t=>`<div class="topic"><div class="topicline"><span>${t}</span><b>--</b></div><div class="track"></div></div>`).join('')}<button class="train" disabled>◎ &nbsp; Train weakest path<small>Complete pre-test to identify weak areas</small></button></div>`).join('')}
function renderPractice(){let r=getSession(),p=load(),b=document.getElementById('resumeBanner');if(b){b.classList.toggle('show',!!r);if(r){resumeText.textContent=`${r.mode} • question ${r.index+1} of ${r.ids.length}`;resumeBtn.onclick=()=>openSession(r)}}renderLocks()}
function renderLocks(){let p=load(),a=document.getElementById('startAdaptive'),e=document.getElementById('startExam');if(a)a.disabled=!p.completedPretest;if(e)e.disabled=!p.completedPretest}
function showExamPicker(){let p=load();if(!p.completedPretest)return alert('Complete the pre-test first.');let host=document.getElementById('quizHost');host.classList.remove('hidden');host.innerHTML=`<div class="card questioncard"><h2>Choose Weekly Full Exam</h2><p>Each exam is a separate fresh 150-question set and must be completed in one sitting.</p><div class="practicegrid">${[3,4,5,6].map(w=>{let done=p.sessions.some(s=>s.mode===`week${w}`&&s.completed);return `<div class="card pcard"><h3>Week ${w}</h3><p>${done?'Completed':'150 questions • one sitting'}</p><button class="enginebtn" data-week="week${w}" ${done?'disabled':''}>${done?'Completed':'Start Exam'}</button></div>`}).join('')}</div></div>`;document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>start(b.dataset.week))}
function relationMastery(rel,p){let a=p.attempts.filter(x=>x.relation===rel);if(!a.length)return null;let base=a.filter(x=>x.ok).length/a.length,hiWrong=a.filter(x=>!x.ok&&x.confidence===100).length,reason=a.filter(x=>x.reasonCorrect===false).length;return Math.max(0,Math.round(base*100-hiWrong*7-reason*3))}
function renderMap(){let p=load(),el=document.getElementById('mapContent');el.innerHTML=[1,2,3,4].map(d=>`<div class="card progresscard" style="margin-bottom:10px"><b>D${d} ${D[d]}</b><div>${REL[d].map(r=>{let m=relationMastery(r,p);return `<span>${r}${m===null?' • --':` • ${m}%`}</span>`}).join('')}</div></div>`).join('')+`<div class="card progresscard"><b>Core loop</b><div class="mapchain">Business objectives <span>→</span> Governance & authority <span>→</span> Strategy <span>→</span> Risk assessment <span>→</span> Risk decision <span>→</span> Program <span>→</span> Controls <span>→</span> Test/evaluate <span>→</span> Monitor/report <span>→</span> Incident/change <span>→</span> Recover <span>→</span> Lessons learned <span>→</span> Reassess risk</div></div>`}
function renderProgress(){let s=stats(),el=document.getElementById('progressContent');if(!s.all.length)return el.innerHTML='<p>No attempts yet. Start the cold pre-test.</p>';let mm={};s.all.filter(x=>!x.ok).forEach(x=>mm[x.mistake]=(mm[x.mistake]||0)+1);let top=Object.entries(mm).sort((a,b)=>b[1]-a[1]).slice(0,10);let hist=s.p.sessions.slice().reverse();el.innerHTML=`<div class="progressgrid">${[1,2,3,4].map(d=>`<div class="card progresscard"><b>D${d} ${D[d]}</b><div style="font-size:28px;font-weight:800;margin:8px 0">${s.by[d].acc===null?'--':Math.round(200+s.by[d].acc*600)}</div><div class="tiny">Cherub training score • ${s.by[d].n} attempts</div></div>`).join('')}</div><div class="card progresscard" style="margin-top:12px"><h3>Reasoning diagnostics</h3><p>High-confidence accuracy: ${s.cal===null?'--':Math.round(s.cal*100)+'%'} • Reasoning accuracy: ${s.reason===null?'--':Math.round(s.reason*100)+'%'} • Distractor elimination: ${s.elim===null?'--':Math.round(s.elim*100)+'%'}</p>${top.map(x=>`<span class="epill">${x[0]}: ${x[1]}</span>`).join(' ')||'No misses yet.'}</div><div class="card progresscard" style="margin-top:12px"><b>Overall training readiness:</b> ${s.score??'--'} <span class="tiny">Training score only; not an official ISACA scaled score.</span></div><div class="card progresscard" style="margin-top:12px"><h3>Exam / session history</h3>${hist.length?hist.map(x=>`<div class="topicline"><span>${x.mode} • ${new Date(x.finishedAt).toLocaleDateString()}</span><b>${Math.round(x.accuracy*100)}%</b></div>`).join(''):'No completed sessions yet.'}</div>`}
function renderSchedule(){let p=load(),el=document.querySelector('#schedule .placeholder');if(!el)return;const done=m=>p.sessions.some(s=>s.mode===m&&s.completed);el.innerHTML=`<h1>Schedule</h1><p>Six-week progression. The baseline drives adaptive work; weekly full exams remain independent one-sitting checks.</p><div class="progressgrid">${[['Week 1','Cold 150Q Pre-Test','pretest',p.completedPretest],['Week 2','Adaptive Hard/Harder every 2–3 days','adaptive',p.sessions.some(s=>s.mode==='adaptive')],['Week 3','Fresh 150Q Full Exam','week3',done('week3')],['Week 4','Fresh 150Q Full Exam','week4',done('week4')],['Week 5','Fresh 150Q Full Exam','week5',done('week5')],['Week 6','Fresh 150Q Full Exam','week6',done('week6')]].map(x=>`<div class="card progresscard"><b>${x[0]}</b><p>${x[1]}</p><span class="epill">${x[3]?'Completed':'Pending'}</span>${x[2]==='adaptive'&&p.completedPretest?'<button class="enginebtn" data-go="adaptive">Practice</button>':''}${/^week/.test(x[2])&&p.completedPretest&&!x[3]?`<button class="enginebtn" data-go="${x[2]}">Start</button>`:''}</div>`).join('')}</div>`;el.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>start(b.dataset.go))}
function renderNotes(){let el=document.querySelector('#notes .placeholder'),v=localStorage.getItem(NK)||'';el.innerHTML=`<h1>Notes</h1><p>Private notes stored in this browser.</p><textarea id="notesBox" style="width:100%;min-height:360px;border:1px solid #d4deeb;border-radius:10px;padding:12px">${v.replace(/</g,'&lt;')}</textarea><p><button class="enginebtn" id="saveNotes">Save Notes</button></p>`;saveNotes.onclick=()=>{localStorage.setItem(NK,notesBox.value);alert('Notes saved.')};}
function renderResources(){let el=document.querySelector('#resources .placeholder');el.innerHTML=`<h1>Resources</h1><div class="card progresscard"><h3>Current exam boundary</h3><p>D1 17% • D2 20% • D3 33% • D4 30%.</p></div><div class="card progresscard" style="margin-top:12px"><h3>Cherub source model</h3><p>Index → referenced locations → domain sections → tables/figures → glossary/acronyms → observed relationship → question.</p><p>The repository stores transformed study data and original Cherub questions, not licensed manual pages or recordings.</p></div>`}
function exportProgress(){let p=load(),blob=new Blob([JSON.stringify({appVersion:M.appVersion,exported:new Date().toISOString(),progress:p,notes:localStorage.getItem(NK)||''},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cherub-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importFile(file){let fr=new FileReader();fr.onload=()=>{try{let x=JSON.parse(fr.result),p=x.progress||x.data||x;if(!p.attempts)throw Error();localStorage.setItem(PK,JSON.stringify({...base(),...p}));if(typeof x.notes==='string')localStorage.setItem(NK,x.notes);clearSession();renderDashboard();renderLocks();alert('Backup imported.')}catch{alert('That file is not a valid Cherub backup.')}};fr.readAsText(file)}
function renderSettings(){let el=document.querySelector('#settings .placeholder'),p=load();el.innerHTML=`<h1>Settings</h1><div class="card progresscard"><h3>Application</h3><p>Version <b>${M.appVersion}</b></p><p>Progress is autosaved locally after every submitted answer. App/content updates are separate from your progress.</p></div><div class="card progresscard" style="margin-top:12px"><h3>Backup & restore</h3><button class="enginebtn" id="sx">Export Backup</button> <button class="enginebtn secondary" id="si">Import Backup</button><input id="sf" type="file" accept="application/json" class="hidden"></div><div class="card progresscard" style="margin-top:12px"><h3>Reset</h3><button class="enginebtn secondary" id="resetAll">Reset All Local Progress</button></div>`;sx.onclick=exportProgress;si.onclick=()=>sf.click();sf.onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);resetAll.onclick=()=>{if(confirm('Reset ALL Cherub progress and notes on this browser?')){localStorage.removeItem(PK);localStorage.removeItem(SK);localStorage.removeItem(NK);renderDashboard();renderLocks();show('dashboard')}}}
function wire(){buildDomains();startPretest.onclick=()=>start('pretest');startAdaptive.onclick=()=>start('adaptive');startExam.onclick=showExamPicker;exportProgress.onclick=exportProgress;importProgress.onclick=()=>importFile.click();importFile.onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);renderDashboard();renderPractice();renderSchedule();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
