from __future__ import annotations

from dataclasses import dataclass
from typing import List, Dict


@dataclass(frozen=True)
class Question:
    id: str
    domain: int
    difficulty: str
    stem: str
    options: Dict[str, str]
    answer: str
    rationale: str
    distractors: Dict[str, str]
    concepts: List[str]


def _q(i: int, domain: int, difficulty: str, stem: str, a: str, b: str, c: str, d: str,
       answer: str, rationale: str, distractors: Dict[str, str], concepts: List[str]) -> Question:
    return Question(
        id=f"D{domain}-{i:03d}",
        domain=domain,
        difficulty=difficulty,
        stem=stem,
        options={"A": a, "B": b, "C": c, "D": d},
        answer=answer,
        rationale=rationale,
        distractors=distractors,
        concepts=concepts,
    )


QUESTIONS: List[Question] = [
    _q(1,1,"hard","A business unit wants to deploy a new customer platform before the enterprise security policy review is complete. What should the information security manager do FIRST?",
       "Block the deployment until every policy is updated","Determine whether the current control requirements adequately address the business risk","Require the business unit to accept all residual risk in writing","Ask internal audit to approve a temporary exception",
       "B","The security manager should first evaluate whether existing requirements and controls sufficiently address the actual risk. Governance decisions should be risk-based and aligned to business objectives, not driven by documentation status alone.",
       {"A":"Premature; a blanket stop may not be justified by risk.","C":"Risk acceptance may be needed later, but only after risk is understood.","D":"Internal audit provides assurance and should not own management approval."},
       ["governance","business alignment","risk-based decision making"]),
    _q(2,1,"hard","Senior management asks which security metric best demonstrates that the security program supports business objectives. Which is BEST?",
       "Number of blocked malware events","Percentage of systems with current antivirus signatures","Reduction in business-impacting risk against approved risk appetite","Number of security awareness emails sent",
       "C","Governance metrics should connect security outcomes to business risk and approved appetite. Technical activity counts are useful operationally but do not best demonstrate strategic alignment.",
       {"A":"Operational volume without business context.","B":"Control hygiene metric, not strategic outcome.","D":"Activity metric, not effectiveness."},
       ["metrics","risk appetite","strategic alignment"]),
    _q(3,1,"hard","A newly appointed CISO discovers that security priorities are being selected mainly by technical teams. What is the MOST important corrective action?",
       "Create a larger security architecture committee","Map security priorities to business objectives and enterprise risk decisions","Increase penetration testing frequency","Require all security purchases to be approved by the CISO",
       "B","Security governance requires prioritization based on business objectives, enterprise risk, and accountable decision rights rather than technical preference.",
       {"A":"May help coordination but does not fix strategic misalignment.","C":"A testing activity does not address governance.","D":"Centralization alone does not create business alignment."},
       ["governance framework","business objectives","decision rights"]),
    _q(4,1,"harder","The board approves a lower cyber risk appetite, but business processes and budgets remain unchanged. What should the security manager do NEXT?",
       "Immediately increase all security controls","Translate the new appetite into measurable tolerances and identify gaps requiring business decisions","Publish the board decision and wait for departments to adjust","Escalate all current risks above the new threshold to regulators",
       "B","A changed appetite must be translated into actionable tolerances, assessed against the current state, and converted into prioritized management decisions.",
       {"A":"Controls should follow assessed gaps, not be increased indiscriminately.","C":"Governance requires active implementation, not passive communication.","D":"Regulatory escalation is not automatically required."},
       ["risk appetite","risk tolerance","governance implementation"]),
    _q(5,1,"hard","Who should ultimately own acceptance of a significant information security risk affecting a critical business process?",
       "The security operations manager","The business owner accountable for the process","The internal auditor","The security architect",
       "B","Risk ownership belongs with the accountable business owner because that role owns the business objective and consequences. Security advises and facilitates.",
       {"A":"Security operations manages controls but does not own business risk.","C":"Audit must remain independent.","D":"Architecture designs controls but does not own business outcomes."},
       ["risk ownership","accountability","governance"]),
    _q(6,1,"hard","A security steering committee receives dozens of technical issues every month and rarely makes decisions. What improvement would provide the MOST value?",
       "Add more technical detail to each issue","Present issues in terms of business impact, risk, options, and decision required","Invite more engineers to the committee","Move all issues to internal audit",
       "B","Governance bodies are most effective when information is decision-oriented and expressed in business risk terms.",
       {"A":"More detail can obscure decisions.","C":"Additional engineers do not solve the governance problem.","D":"Audit should not own operational governance."},
       ["steering committee","executive communication","decision support"]),
    _q(7,1,"harder","An acquired company has a mature security program that differs from the parent company's standards. What should be done FIRST?",
       "Replace all acquired-company controls with parent controls","Assess how the acquired program aligns to enterprise objectives, risk appetite, and mandatory requirements","Allow the acquired program to operate indefinitely","Require the acquired CISO to sign a risk acceptance",
       "B","Integration should start with an assessment of alignment, obligations, and risk. Equivalent or stronger controls may be acceptable even if implemented differently.",
       {"A":"Creates unnecessary disruption before assessing equivalence.","C":"Indefinite independence may leave governance gaps.","D":"Acceptance is premature before evaluation."},
       ["M&A governance","control equivalence","risk alignment"]),
    _q(8,1,"hard","A regulator issues new requirements that affect only one business service. What should the security manager do FIRST?",
       "Apply the requirements to every system enterprise-wide","Determine applicability, affected assets, and compliance obligations","Purchase a compliance automation platform","Ask audit to certify compliance",
       "B","The first step is understanding applicability and scope before selecting controls or assurance activities.",
       {"A":"May create unnecessary cost.","C":"Tooling before requirements analysis is premature.","D":"Audit cannot certify before implementation."},
       ["legal and regulatory requirements","scope","compliance governance"]),
    _q(9,1,"hard","A board member asks why cybersecurity investments should be prioritized over another business initiative. The BEST response is to compare:",
       "Security vendor rankings","Expected reduction in business risk and impact on strategic objectives","Number of open vulnerabilities","Industry breach headlines",
       "B","Investment decisions should be made using business value, risk reduction, and strategic impact.",
       {"A":"Vendor rankings are not business justification.","C":"Vulnerability counts lack business context.","D":"Headlines may inform awareness but are not an investment case."},
       ["business case","risk reduction","investment governance"]),
    _q(10,1,"harder","Security responsibilities are documented, but incidents repeatedly reveal that no one knows who can make time-critical risk decisions. What is MOST likely missing?",
       "A vulnerability scanner","Defined decision authority and escalation paths","More security awareness training","A larger SOC",
       "B","Documented responsibilities are insufficient if decision rights and escalation authority are unclear during critical events.",
       {"A":"Tooling is unrelated.","C":"Training may help awareness but not governance authority.","D":"Staffing does not fix unclear accountability."},
       ["roles and responsibilities","decision authority","escalation"]),

    _q(1,2,"hard","A critical application has several known vulnerabilities, but exploitation would require internal access and compensating controls are strong. What should the risk manager do FIRST?",
       "Order immediate remediation of every vulnerability","Assess likelihood and business impact in the current control environment","Accept the risk because compensating controls exist","Report the application as noncompliant",
       "B","Risk treatment decisions should follow analysis of likelihood, impact, and existing controls rather than vulnerability severity alone.",
       {"A":"May waste resources if actual risk is low.","C":"Acceptance before assessment is premature.","D":"Compliance status is not the same as risk level."},
       ["risk assessment","likelihood","impact","compensating controls"]),
    _q(2,2,"harder","Two business units rate the same threat very differently. What is the BEST way to improve consistency?",
       "Use the higher rating automatically","Define common risk criteria, scales, and impact guidance tied to business objectives","Require the security team to assign all risk ratings","Average the two ratings",
       "B","Consistent risk decisions require shared criteria, definitions, and calibrated scales while preserving accountable ownership.",
       {"A":"Conservative but not necessarily accurate.","C":"Removes business ownership.","D":"Averaging incompatible judgments does not improve methodology."},
       ["risk methodology","risk criteria","consistency"]),
    _q(3,2,"hard","A vendor processes sensitive customer data. Which action provides the BEST basis for deciding whether the vendor's risk is acceptable?",
       "Review the vendor's marketing materials","Evaluate contractual, control, legal, resilience, and data-handling risks against enterprise requirements","Require the vendor to have the same tools as the enterprise","Accept a recent penetration test as sufficient evidence",
       "B","Third-party risk should be evaluated comprehensively against enterprise requirements and business context.",
       {"A":"Marketing is not assurance evidence.","C":"Control objectives matter more than identical products.","D":"A pen test covers only part of the risk."},
       ["third-party risk","due diligence","data protection"]),
    _q(4,2,"hard","A business owner rejects a recommended control because the cost exceeds expected loss. What should the security manager do?",
       "Implement the control anyway","Validate the risk analysis and present viable treatment options to the accountable owner","Escalate directly to law enforcement","Remove the risk from the register",
       "B","Security should ensure the decision is informed, based on sound analysis, and made by the accountable owner within governance rules.",
       {"A":"Security should not usurp business risk ownership.","C":"No crime is implied.","D":"Rejected treatment does not erase the risk."},
       ["risk treatment","cost-benefit","risk ownership"]),
    _q(5,2,"harder","A risk register contains hundreds of entries but executives cannot tell which risks require decisions. What improvement is MOST important?",
       "Add more vulnerabilities to each entry","Prioritize risks using business impact, likelihood, ownership, treatment status, and appetite thresholds","Sort the register alphabetically","Move the register into a new GRC tool",
       "B","A risk register should support decision-making by clearly showing severity, accountability, treatment, and relationship to appetite.",
       {"A":"More technical detail can reduce clarity.","C":"Alphabetical order does not prioritize risk.","D":"A tool cannot fix poor risk information design."},
       ["risk register","prioritization","risk appetite"]),
    _q(6,2,"hard","A control reduces likelihood but does not reduce impact. How should this be reflected in residual risk?",
       "Residual risk is zero","Likelihood should be reassessed while impact remains based on plausible business consequences","Impact should automatically be reduced by the same amount","The control should be ignored",
       "B","Residual risk should reflect how a control actually changes the risk components. A preventive control may reduce likelihood without changing impact.",
       {"A":"No ordinary control makes risk automatically zero.","C":"Likelihood and impact are not interchangeable.","D":"A meaningful control must be considered."},
       ["residual risk","control effectiveness","risk analysis"]),
    _q(7,2,"harder","A major cloud provider refuses custom audit rights but offers independent assurance reports. What should the organization do FIRST?",
       "Reject the provider automatically","Determine whether the available assurance is sufficient for the organization's risk and compliance requirements","Accept the provider because it is well known","Require the security team to perform an unauthorized test",
       "B","The organization should assess whether alternative assurance evidence meets its specific obligations and risk needs.",
       {"A":"May eliminate viable providers unnecessarily.","C":"Reputation is not sufficient assurance.","D":"Unauthorized testing is inappropriate and may violate agreements."},
       ["cloud risk","third-party assurance","due diligence"]),
    _q(8,2,"hard","A newly identified risk exceeds approved tolerance, but no feasible treatment can be completed for six months. What is the BEST next step?",
       "Delete the risk until treatment is available","Escalate to the appropriate risk owner with interim options and explicit decision requirements","Assume management accepts it","Change the risk rating to fit tolerance",
       "B","Risks beyond tolerance require accountable escalation, interim treatment consideration, and explicit decisions.",
       {"A":"Hides material risk.","C":"Acceptance must be explicit.","D":"Ratings must reflect reality, not desired thresholds."},
       ["risk escalation","risk tolerance","interim controls"]),
    _q(9,2,"hard","What is the PRIMARY reason to perform risk assessments periodically and after significant change?",
       "To generate more audit evidence","Because threats, assets, controls, business impact, and assumptions change over time","To ensure every risk is rated high","To replace continuous monitoring",
       "B","Risk is dynamic. Assessments must be refreshed when the environment or assumptions materially change.",
       {"A":"Audit evidence is secondary.","C":"Ratings should be objective.","D":"Periodic assessment complements rather than replaces monitoring."},
       ["risk lifecycle","change management","risk monitoring"]),
    _q(10,2,"harder","An executive wants a single cyber risk score for the whole enterprise. What is the BEST response?",
       "Provide one number without assumptions","Provide an aggregated view with clear methodology, uncertainty, major drivers, and drill-down to material risks","Refuse because risk cannot be measured","Use the highest vulnerability score as the enterprise score",
       "B","Aggregation can support governance if limitations and material drivers remain visible. A single opaque number can conceal important differences.",
       {"A":"Creates false precision.","C":"Risk can be assessed, though imperfectly.","D":"Vulnerability severity is not enterprise risk."},
       ["risk reporting","aggregation","uncertainty"]),

    _q(1,3,"hard","A security program has many controls but no clear link to business priorities. What should the program manager do FIRST?",
       "Buy a larger SIEM","Map program objectives and capabilities to business requirements, risks, and approved priorities","Increase phishing simulations","Add more controls from a framework",
       "B","An effective program starts with business and risk requirements. Controls and capabilities should then be organized to meet those requirements.",
       {"A":"Tooling does not establish program alignment.","C":"A useful activity but not the foundational issue.","D":"Framework controls should be selected based on need."},
       ["security program","business alignment","program objectives"]),
    _q(2,3,"harder","A security control is implemented globally but consistently bypassed by users because it disrupts a critical workflow. What should be done FIRST?",
       "Discipline all users who bypass it","Evaluate whether the control design meets the required objective while supporting the business process","Remove the control immediately","Increase monitoring without changing the control",
       "B","Controls must achieve their objective in the actual operating environment. Repeated bypass is evidence that design or implementation should be reassessed.",
       {"A":"May treat the symptom, not the control-design problem.","C":"Removal without assessment may expose risk.","D":"Monitoring alone does not correct a dysfunctional control."},
       ["control design","business process integration","control effectiveness"]),
    _q(3,3,"hard","Which measure BEST demonstrates security awareness program effectiveness?",
       "Number of training slides","Training attendance alone","Observable reduction in risky behavior and improved reporting tied to defined objectives","Number of reminder emails",
       "C","Effectiveness is demonstrated by measurable behavior and risk outcomes, not merely activity completion.",
       {"A":"Output metric only.","B":"Attendance does not demonstrate learning or behavior change.","D":"Communication volume is an activity metric."},
       ["awareness","metrics","behavior change"]),
    _q(4,3,"hard","A project team asks the security manager to approve a design. What is the BEST role for the security manager?",
       "Own the project's business risk","Provide security requirements and risk advice so the accountable business/project owner can make informed decisions","Replace the solution architect","Guarantee the system will never be breached",
       "B","Security should define requirements, assess risk, and advise decision-makers while business and project owners retain accountability.",
       {"A":"Business risk ownership stays with accountable management.","C":"Security does not replace architecture ownership.","D":"No security manager can guarantee absolute security."},
       ["security architecture","advisory role","accountability"]),
    _q(5,3,"harder","A key control has passed design review but fails frequently in production. Which action is MOST important?",
       "Continue reporting the control as effective","Assess operating effectiveness, root cause, and residual risk, then prioritize remediation","Rewrite the policy only","Increase the inherent risk score without investigating",
       "B","Design effectiveness and operating effectiveness are distinct. Repeated production failure requires evidence-based reassessment and remediation.",
       {"A":"Misstates control status.","C":"Policy text may not solve operational failure.","D":"Residual rather than inherent risk is affected by control performance."},
       ["control testing","operating effectiveness","remediation"]),
    _q(6,3,"hard","The organization has limited funds for security projects. Which approach BEST supports prioritization?",
       "Fund projects requested by the largest departments","Rank initiatives by business risk reduction, mandatory obligations, dependencies, and strategic value","Fund the newest technologies first","Divide funds equally across security teams",
       "B","Program investment should be prioritized according to business value, risk reduction, obligations, and dependencies.",
       {"A":"Department size is not a risk criterion.","C":"Novelty is not value.","D":"Equal distribution ignores differing risk and impact."},
       ["portfolio prioritization","business case","security investment"]),
    _q(7,3,"harder","A security architecture standard conflicts with a new product's performance requirements. What should happen FIRST?",
       "Waive the standard automatically","Clarify the control objective and evaluate alternative designs that satisfy both security and business requirements","Force compliance regardless of business impact","Remove the standard from the security program",
       "B","The objective is to meet required security outcomes while enabling business needs. Alternative controls or architectures should be evaluated before accepting or rejecting exceptions.",
       {"A":"Exception without analysis is weak governance.","C":"May create unacceptable business impact unnecessarily.","D":"A single conflict does not invalidate the standard."},
       ["security architecture","exceptions","compensating controls"]),
    _q(8,3,"hard","What is the MOST important purpose of a security program roadmap?",
       "List every available security product","Sequence capabilities and investments to close prioritized gaps and support target business outcomes","Replace the risk register","Serve as the incident response plan",
       "B","A roadmap translates strategy and priorities into sequenced initiatives, dependencies, and capability improvements.",
       {"A":"Product cataloging is not a roadmap.","C":"Risk and roadmap functions are related but distinct.","D":"Incident response planning has a different purpose."},
       ["roadmap","capability planning","program management"]),
    _q(9,3,"hard","A new detection technology produces thousands of alerts but identifies few meaningful incidents. What should the manager evaluate FIRST?",
       "Whether alert volume is higher than peers","Whether use cases, tuning, data quality, and detection objectives align with relevant threats and business risk","Whether analysts can close alerts faster","Whether another vendor has more features",
       "B","Detection effectiveness depends on relevant use cases, appropriate telemetry, tuning, and risk alignment—not raw alert volume.",
       {"A":"Peer volume is not an effectiveness measure.","C":"Speed matters but cannot compensate for poor signal quality.","D":"Feature count does not establish effectiveness."},
       ["security operations","use cases","control effectiveness"]),
    _q(10,3,"harder","Several security projects are individually successful, yet enterprise risk remains unchanged. What should management investigate FIRST?",
       "Whether project teams used enough agile ceremonies","Whether projects target the organization's highest-priority risk drivers and whether benefits are measured at outcome level","Whether employees like the security tools","Whether project budgets were fully spent",
       "B","Program success should be measured by outcomes and risk reduction. Successful delivery of misaligned projects may produce little enterprise benefit.",
       {"A":"Process adherence does not guarantee risk reduction.","C":"User satisfaction alone is insufficient.","D":"Budget utilization is not an outcome."},
       ["program effectiveness","benefits realization","risk reduction"]),

    _q(1,4,"hard","A suspected breach is reported, but evidence is incomplete and business impact is uncertain. What should the incident manager do FIRST?",
       "Publicly announce a breach","Activate the defined triage process to validate the event, establish scope, severity, and required escalation","Rebuild all affected systems immediately","Wait until every fact is known before acting",
       "B","Early incident handling should validate the event, determine scope and severity, preserve evidence, and trigger appropriate escalation.",
       {"A":"External communication should follow validated facts and defined authority.","C":"Premature rebuilding can destroy evidence and disrupt containment.","D":"Perfect information is not required to begin triage."},
       ["incident triage","severity","escalation"]),
    _q(2,4,"harder","During a ransomware incident, operations wants to restore systems immediately while forensics wants to preserve evidence. What is the BEST approach?",
       "Always prioritize forensics","Always prioritize restoration","Use the incident governance process to balance safety, business recovery, legal/evidence needs, and containment objectives","Let the most senior technician decide",
       "C","Incident decisions should be risk-based and coordinated across business, legal, technical, and recovery needs under established authority.",
       {"A":"May unnecessarily prolong critical business disruption.","B":"May destroy evidence or reintroduce compromise.","D":"Authority should be defined by the response process, not ad hoc seniority."},
       ["incident governance","forensics","recovery","business continuity"]),
    _q(3,4,"hard","What is the PRIMARY purpose of incident classification?",
       "Determine which analyst gets credit","Apply consistent severity, response, escalation, and communication criteria","Ensure every incident is labeled critical","Replace root-cause analysis",
       "B","Classification enables consistent decisions about priority, escalation, resources, and communications.",
       {"A":"Personnel credit is irrelevant.","C":"Severity must reflect facts.","D":"Classification and root-cause analysis serve different purposes."},
       ["incident classification","severity","response process"]),
    _q(4,4,"hard","A business unit discovers evidence of data exfiltration. Who should determine whether regulators or customers must be notified?",
       "The SOC analyst alone","Authorized management with legal/privacy input according to applicable requirements and the incident communication plan","The attacker","The external penetration tester",
       "B","Notification decisions require authorized governance and legal/privacy analysis because obligations depend on facts, jurisdiction, contracts, and timing.",
       {"A":"Analysts supply facts but should not unilaterally make legal notification decisions.","C":"The attacker has no governance role.","D":"A tester is not accountable for organizational notifications."},
       ["breach notification","legal requirements","incident communications"]),
    _q(5,4,"harder","After containment, the team restores systems but skips lessons learned because operations is busy. What is the GREATEST risk?",
       "The incident ticket may be shorter","Root causes, control weaknesses, and response-process failures may remain unresolved and recur","The restored systems will automatically fail","The organization will lose all forensic evidence",
       "B","Post-incident review is essential for identifying root causes, systemic weaknesses, and improvements to prevention, detection, response, and recovery.",
       {"A":"Ticket length is not material.","C":"Skipping lessons learned does not guarantee system failure.","D":"Evidence preservation is a separate process and may already be complete."},
       ["lessons learned","root cause","continuous improvement"]),
    _q(6,4,"hard","A tabletop exercise reveals that executives and technical responders use different severity definitions. What should be done NEXT?",
       "Stop running exercises","Reconcile severity criteria, decision thresholds, escalation paths, and communication expectations","Let each team keep its own definitions","Purchase a new incident platform",
       "B","Exercises are intended to expose coordination gaps. Common severity and escalation criteria are necessary for coherent response.",
       {"A":"The exercise produced useful findings.","C":"Different definitions create delay and confusion.","D":"Technology does not solve governance inconsistency."},
       ["tabletop exercises","severity criteria","communications"]),
    _q(7,4,"harder","A critical supplier suffers a cyber incident that may affect the organization. What should the incident manager do FIRST?",
       "Assume internal compromise","Invoke third-party incident procedures, validate exposure and dependencies, and coordinate with the supplier and business owners","Terminate the supplier immediately","Ignore the event until internal alerts appear",
       "B","Third-party incidents require rapid assessment of actual exposure, dependencies, and coordinated response using defined procedures.",
       {"A":"Assumption without validation can cause poor decisions.","C":"Termination may be disproportionate and disruptive.","D":"Waiting may allow preventable impact."},
       ["third-party incident response","dependencies","coordination"]),
    _q(8,4,"hard","Which metric BEST indicates incident response capability is improving?",
       "Number of incidents reported","Reduction in time to detect, contain, and recover for comparable incidents while meeting response quality objectives","Number of pages in the incident plan","Number of SOC dashboards",
       "B","Capability improvement is demonstrated by better response outcomes and quality, not document or dashboard volume.",
       {"A":"Volume may rise for many reasons.","C":"Plan length is not effectiveness.","D":"Dashboard count is an activity measure."},
       ["incident metrics","MTTD","containment","recovery"]),
    _q(9,4,"harder","An incident commander learns that a containment action could stop an attack but would also interrupt a safety-critical service. What is the BEST next step?",
       "Execute containment immediately without consultation","Escalate under predefined authority and coordinate a risk-based action that considers safety, business impact, and attack progression","Do nothing","Ask the attacker for permission",
       "B","High-impact containment decisions must balance cyber risk with safety and operational consequences under defined authority.",
       {"A":"Could create greater harm.","C":"Inaction may allow the incident to worsen.","D":"The attacker is not a legitimate decision-maker."},
       ["containment","safety","decision authority"]),
    _q(10,4,"hard","Why should incident response plans be exercised regularly?",
       "To guarantee incidents will not occur","To validate roles, decisions, communications, dependencies, and procedures before a real event","To satisfy only the SOC team","To replace technical monitoring",
       "B","Exercises reveal practical gaps in coordination, authority, communications, dependencies, and procedures before real incidents occur.",
       {"A":"Exercises cannot eliminate incidents.","C":"Response is cross-functional.","D":"Exercises complement rather than replace monitoring."},
       ["incident exercises","preparedness","validation"]),
]


def all_questions() -> List[Question]:
    return list(QUESTIONS)


def by_domain(domain: int) -> List[Question]:
    return [q for q in QUESTIONS if q.domain == domain]
