let current=null, selected=null, nextQuestion=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function show(id){['home','quiz','reveal','dashboard'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});return r.json()}
function renderQuestion(q,session){current={q,session};selected=null;nextQuestion=null;$('#submit').disabled=true;$('#stem').textContent=q.stem;$('#domain').textContent=`Domain ${q.domain}: ${q.domain_name}`;$('#difficulty').textContent=q.difficulty.toUpperCase();$('#progress').textContent=`Question ${session.current_index+1} of ${session.question_ids.length}`;$('#options').innerHTML='';Object.entries(q.options).forEach(([k,v])=>{const b=document.createElement('button');b.textContent=`${k}. ${v}`;b.onclick=()=>{$$('.options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=k;$('#submit').disabled=false};$('#options').appendChild(b)});$('#reasoning').value='';$('#confidence').value=3;$('#confidenceValue').textContent='3';show('quiz')}
async function start(mode){const d=await api('/api/start',{method:'POST',body:JSON.stringify({mode,total:20})});renderQuestion(d.question,d.session)}
$$('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
$('#confidence').oninput=e=>$('#confidenceValue').textContent=e.target.value;
$('#submit').onclick=async()=>{if(!selected)return;const d=await api('/api/answer',{method:'POST',body:JSON.stringify({choice:selected,confidence:+$('#confidence').value,reasoning:$('#reasoning').value})});$('#resultTitle').textContent=d.record.correct?`Correct — ${d.answer}`:`Not quite — correct answer: ${d.answer}`;$('#rationale').textContent=d.rationale;$('#distractors').innerHTML='';Object.entries(d.distractors).forEach(([k,v])=>{const p=document.createElement('div');p.className='why';p.textContent=`${k}: ${v}`;$('#distractors').appendChild(p)});$('#concepts').innerHTML=d.concepts.map(x=>`<span>${x}</span>`).join('');nextQuestion=d.next_question||null;current.session.current_index=(current.session.current_index||0)+1;current.session.complete=d.complete;$('#next').textContent=d.complete?'View dashboard':'Next question';show('reveal')};
$('#next').onclick=()=>{if(current.session.complete){dashboard()}else if(nextQuestion){renderQuestion(nextQuestion,current.session)}};
async function dashboard(){const d=await api('/api/status');const stats=d.state.domain_stats||{};let html='<div class="scoregrid">';Object.entries(d.domains).forEach(([id,cfg])=>{const s=stats[id]||{attempted:0,correct:0,confidence_sum:0};const acc=s.attempted?Math.round(100*s.correct/s.attempted):0;const conf=s.attempted?(s.confidence_sum/s.attempted).toFixed(1):'—';html+=`<div class="stat"><span>Domain ${id}</span><strong>${acc}%</strong><small>${cfg.name}<br>${s.correct}/${s.attempted} correct · confidence ${conf}/5</small></div>`});html+='</div>';const sessions=d.state.sessions||[];html+=`<p class="muted">Completed sessions: ${sessions.length}</p>`;$('#stats').innerHTML=html;show('dashboard')}
$('#dashboardBtn').onclick=dashboard;$('#backHome').onclick=()=>show('home');
$('#resumeBtn').onclick=async()=>{const d=await api('/api/current');if(d.session&&d.question)renderQuestion(d.question,d.session)};
(async()=>{const d=await api('/api/current');if(d.session&&!d.session.complete)$('#resumeWrap').classList.remove('hidden')})();
